// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Available authorization mode of a Redis cluster.
public enum AuthorizationMode: Codable, Equatable, Sendable {
  /// Not set.
  case authModeUnspecified
  /// IAM basic authorization mode
  case authModeIamAuth
  /// Authorization disabled mode
  case authModeDisabled
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .authModeUnspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .authModeUnspecified: return 0
    case .authModeIamAuth: return 1
    case .authModeDisabled: return 2
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .authModeUnspecified: return "AUTH_MODE_UNSPECIFIED"
    case .authModeIamAuth: return "AUTH_MODE_IAM_AUTH"
    case .authModeDisabled: return "AUTH_MODE_DISABLED"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AuthorizationMode/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "AUTH_MODE_UNSPECIFIED": self = .authModeUnspecified
    case "AUTH_MODE_IAM_AUTH": self = .authModeIamAuth
    case "AUTH_MODE_DISABLED": self = .authModeDisabled
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AuthorizationMode/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .authModeUnspecified
    case 1: self = .authModeIamAuth
    case 2: self = .authModeDisabled
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .authModeUnspecified: return try container.encode(0)
    case .authModeIamAuth: return try container.encode(1)
    case .authModeDisabled: return try container.encode(2)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
