// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleType

/// The automated backup config for a cluster.
public struct AutomatedBackupConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. The automated backup mode. If the mode is disabled, the other
  /// fields will be ignored.
  public var automatedBackupMode: AutomatedBackupConfig.AutomatedBackupMode =
    AutomatedBackupConfig.AutomatedBackupMode()

  /// Optional. How long to keep automated backups before the backups are
  /// deleted. The value should be between 1 day and 365 days. If not specified,
  /// the default value is 35 days.
  public var retention: GoogleCloudWKT.Duration? = nil

  /// The schedule of automated backups.
  public var schedule: OneOf_Schedule? = nil

  /// Initialize a new instance of `AutomatedBackupConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AutomatedBackupConfig().with { $0.fixedFrequencySchedule = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case fixedFrequencySchedule = "fixedFrequencySchedule"
    case automatedBackupMode = "automatedBackupMode"
    case retention = "retention"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.automatedBackupMode = try container.decode(
      AutomatedBackupConfig.AutomatedBackupMode.self, forKey: .automatedBackupMode)
    self.retention = try container.decodeIfPresent(GoogleCloudWKT.Duration.self, forKey: .retention)

    var schedule: OneOf_Schedule? = nil
    let scheduleCheckAndSet = {
      if schedule != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'schedule'"))
      }
      schedule = $0
    }
    if let fixedFrequencySchedule = try container.decodeIfPresent(
      AutomatedBackupConfig.FixedFrequencySchedule?.self, forKey: .fixedFrequencySchedule)
    {
      try scheduleCheckAndSet(.fixedFrequencySchedule(fixedFrequencySchedule))
    }
    self.schedule = schedule
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.automatedBackupMode, forKey: .automatedBackupMode)
    try container.encode(self.retention, forKey: .retention)

    if let choice = self.schedule {
      switch choice {
      case .fixedFrequencySchedule(let value):
        try container.encode(value, forKey: .fixedFrequencySchedule)
      }
    }
  }

  /// This schedule allows the backup to be triggered at a fixed frequency
  /// (currently only daily is supported).
  public struct FixedFrequencySchedule: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. The start time of every automated backup in UTC. It must be set
    /// to the start of an hour. This field is required.
    public var startTime: GoogleType.TimeOfDay? = nil

    /// Initialize a new instance of `FixedFrequencySchedule`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FixedFrequencySchedule().with { $0.startTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.redis.cluster.v1.AutomatedBackupConfig.FixedFrequencySchedule"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The automated backup mode.
  public enum AutomatedBackupMode: Codable, Equatable, Sendable {
    /// Default value. Automated backup config is not specified.
    case unspecified
    /// Automated backup config disabled.
    case disabled
    /// Automated backup config enabled.
    case enabled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .disabled: return 1
      case .enabled: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "AUTOMATED_BACKUP_MODE_UNSPECIFIED"
      case .disabled: return "DISABLED"
      case .enabled: return "ENABLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AutomatedBackupMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "AUTOMATED_BACKUP_MODE_UNSPECIFIED": self = .unspecified
      case "DISABLED": self = .disabled
      case "ENABLED": self = .enabled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AutomatedBackupMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .disabled
      case 2: self = .enabled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .disabled: return try container.encode(1)
      case .enabled: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The schedule of automated backups.
  public enum OneOf_Schedule: Codable, Equatable, Sendable {
    /// Optional. Trigger automated backups at a fixed frequency.
    indirect case fixedFrequencySchedule(AutomatedBackupConfig.FixedFrequencySchedule?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.redis.cluster.v1.AutomatedBackupConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
