// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Backup of a cluster.
public struct Backup: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. Full resource path of the backup. the last part of the name is
  /// the backup id with the following format: [YYYYMMDDHHMMSS]_[Shorted Cluster
  /// UID] OR customer specified while backup cluster. Example:
  /// 20240515123000_1234
  public var name: Swift.String = Swift.String()

  /// Output only. The time when the backup was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Cluster resource path of this backup.
  public var cluster: Swift.String = Swift.String()

  /// Output only. Cluster uid of this backup.
  public var clusterUid: Swift.String = Swift.String()

  /// Output only. Total size of the backup in bytes.
  public var totalSizeBytes: Swift.Int64 = Swift.Int64()

  /// Output only. The time when the backup will expire.
  public var expireTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. redis-7.2, valkey-7.5
  public var engineVersion: Swift.String = Swift.String()

  /// Output only. List of backup files of the backup.
  public var backupFiles: [BackupFile] = []

  /// Output only. Node type of the cluster.
  public var nodeType: NodeType = NodeType()

  /// Output only. Number of replicas for the cluster.
  public var replicaCount: Swift.Int32 = Swift.Int32()

  /// Output only. Number of shards for the cluster.
  public var shardCount: Swift.Int32 = Swift.Int32()

  /// Output only. Type of the backup.
  public var backupType: Backup.BackupType = Backup.BackupType()

  /// Output only. State of the backup.
  public var state: Backup.State = Backup.State()

  /// Output only. Encryption information of the backup.
  public var encryptionInfo: EncryptionInfo? = nil

  /// Output only. System assigned unique identifier of the backup.
  public var uid: Swift.String = Swift.String()

  /// Initialize a new instance of `Backup`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Backup().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Type of the backup.
  public enum BackupType: Codable, Equatable, Sendable {
    /// The default value, not set.
    case unspecified
    /// On-demand backup.
    case onDemand
    /// Automated backup.
    case automated
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .onDemand: return 1
      case .automated: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "BACKUP_TYPE_UNSPECIFIED"
      case .onDemand: return "ON_DEMAND"
      case .automated: return "AUTOMATED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:BackupType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "BACKUP_TYPE_UNSPECIFIED": self = .unspecified
      case "ON_DEMAND": self = .onDemand
      case "AUTOMATED": self = .automated
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:BackupType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .onDemand
      case 2: self = .automated
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .onDemand: return try container.encode(1)
      case .automated: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// State of the backup.
  public enum State: Codable, Equatable, Sendable {
    /// The default value, not set.
    case unspecified
    /// The backup is being created.
    case creating
    /// The backup is active to be used.
    case active
    /// The backup is being deleted.
    case deleting
    /// The backup is currently suspended due to reasons like project deletion,
    /// billing account closure, etc.
    case suspended
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .deleting: return 3
      case .suspended: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .deleting: return "DELETING"
      case .suspended: return "SUSPENDED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "DELETING": self = .deleting
      case "SUSPENDED": self = .suspended
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .deleting
      case 4: self = .suspended
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .active: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .suspended: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.redis.cluster.v1.Backup"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
