// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// BackupCollection of a cluster.
public struct BackupCollection: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. Full resource path of the backup collection.
  public var name: Swift.String = Swift.String()

  /// Output only. The cluster uid of the backup collection.
  public var clusterUid: Swift.String = Swift.String()

  /// Output only. The full resource path of the cluster the backup collection
  /// belongs to. Example:
  /// projects/{project}/locations/{location}/clusters/{cluster}
  public var cluster: Swift.String = Swift.String()

  /// Output only. The KMS key used to encrypt the backups under this backup
  /// collection.
  public var kmsKey: Swift.String = Swift.String()

  /// Output only. System assigned unique identifier of the backup collection.
  public var uid: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BackupCollection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupCollection().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let clusterUid = CodingKeys(stringValue: "clusterUid")
    static let cluster = CodingKeys(stringValue: "cluster")
    static let kmsKey = CodingKeys(stringValue: "kmsKey")
    static let uid = CodingKeys(stringValue: "uid")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "clusterUid",
      "cluster",
      "kmsKey",
      "uid",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clusterUid) {
      self.clusterUid = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cluster) {
      self.cluster = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKey) {
      self.kmsKey = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.clusterUid, forKey: .clusterUid)
    try container.encode(self.cluster, forKey: .cluster)
    try container.encode(self.kmsKey, forKey: .kmsKey)
    try container.encode(self.uid, forKey: .uid)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.redis.cluster.v1.BackupCollection"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
