// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Redis cluster certificate authority
public struct CertificateAuthority: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. Unique name of the resource in this scope including project,
  /// location and cluster using the form:
  ///     `projects/{project}/locations/{location}/clusters/{cluster}/certificateAuthority`
  public var name: Swift.String = Swift.String()

  /// server ca information
  public var serverCa: OneOf_ServerCa? = nil

  /// Initialize a new instance of `CertificateAuthority`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CertificateAuthority().with { $0.managedServerCa = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case managedServerCa = "managedServerCa"
    case name = "name"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)

    var serverCa: OneOf_ServerCa? = nil
    let serverCaCheckAndSet = {
      if serverCa != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'serverCa'"))
      }
      serverCa = $0
    }
    if let managedServerCa = try container.decodeIfPresent(
      CertificateAuthority.ManagedCertificateAuthority?.self, forKey: .managedServerCa)
    {
      try serverCaCheckAndSet(.managedServerCa(managedServerCa))
    }
    self.serverCa = serverCa
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)

    if let choice = self.serverCa {
      switch choice {
      case .managedServerCa(let value):
        try container.encode(value, forKey: .managedServerCa)
      }
    }
  }

  public struct ManagedCertificateAuthority: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The PEM encoded CA certificate chains for redis managed
    /// server authentication
    public var caCerts: [CertificateAuthority.ManagedCertificateAuthority.CertChain] = []

    /// Initialize a new instance of `ManagedCertificateAuthority`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ManagedCertificateAuthority().with { $0.caCerts = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public struct CertChain: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// The certificates that form the CA chain, from leaf to root order.
      public var certificates: [Swift.String] = []

      /// Initialize a new instance of `CertChain`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = CertChain().with { $0.certificates = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.redis.cluster.v1.CertificateAuthority.ManagedCertificateAuthority.CertChain"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.redis.cluster.v1.CertificateAuthority.ManagedCertificateAuthority"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// server ca information
  public enum OneOf_ServerCa: Codable, Equatable, Sendable {
    indirect case managedServerCa(CertificateAuthority.ManagedCertificateAuthority?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.redis.cluster.v1.CertificateAuthority"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
