// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Configures and manages Cloud Memorystore for Redis clusters
///
/// Google Cloud Memorystore for Redis Cluster
///
/// The `redis.googleapis.com` service implements the Google Cloud Memorystore
/// for Redis API and defines the following resource model for managing Redis
/// clusters:
/// * The service works with a collection of cloud projects, named: `/projects/*`
/// * Each project has a collection of available locations, named: `/locations/*`
/// * Each location has a collection of Redis clusters, named: `/clusters/*`
/// * As such, Redis clusters are resources of the form:
///   `/projects/{project_id}/locations/{location_id}/clusters/{instance_id}`
///
/// Note that location_id must be a GCP `region`; for example:
/// * `projects/redpepper-1290/locations/us-central1/clusters/my-redis`
///
/// @Snippet(path: "CloudRedisClusterQuickstart")
public final class CloudRedisClusterClient: Clients.CloudRedisClusterProtocol, Sendable {
  let inner: any Clients.CloudRedisClusterStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `CloudRedisClusterClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.CloudRedisClusterStub = try Clients.CloudRedisClusterTransport(options)
    inner = Clients.CloudRedisClusterRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.CloudRedisClusterLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists all Redis clusters owned by a project in either the specified
  /// location (region) or all locations.
  ///
  /// The location should have the following format:
  ///
  /// * `projects/{project_id}/locations/{location_id}`
  ///
  /// If `location_id` is specified as `-` (wildcard), then all regions
  /// available to the project are queried, and the results are aggregated.
  ///
  /// @Snippet(path: "CloudRedisCluster_ListClusters")
  public func listClusters(
    request: ListClustersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.ListClustersResponse {
    try await self.inner.listClusters(request: request, options: options)
  }

  /// Gets the details of a specific Redis cluster.
  ///
  /// @Snippet(path: "CloudRedisCluster_GetCluster")
  public func getCluster(
    request: GetClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.Cluster {
    try await self.inner.getCluster(request: request, options: options)
  }

  /// Updates the metadata and configuration of a specific Redis cluster.
  ///
  /// Completed longrunning.Operation will contain the new cluster object
  /// in the response field. The returned operation is automatically deleted
  /// after a few hours, so there is no need to call DeleteOperation.
  ///
  /// @Snippet(path: "CloudRedisCluster_UpdateCluster")
  public func updateCluster(
    request: UpdateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateCluster(request: request, options: options)
  }

  /// Updates the metadata and configuration of a specific Redis cluster.
  ///
  /// Completed longrunning.Operation will contain the new cluster object
  /// in the response field. The returned operation is automatically deleted
  /// after a few hours, so there is no need to call DeleteOperation.
  ///
  /// @Snippet(path: "CloudRedisCluster_UpdateCluster")
  public func updateClusterPollingUntilDone(
    request: UpdateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      return try op._extractStatus(Cluster.self)
    }
    let rawOp = try await self.updateCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a specific Redis cluster. Cluster stops serving and data is
  /// deleted.
  ///
  /// @Snippet(path: "CloudRedisCluster_DeleteCluster")
  public func deleteCluster(
    request: DeleteClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteCluster(request: request, options: options)
  }

  /// Deletes a specific Redis cluster. Cluster stops serving and data is
  /// deleted.
  ///
  /// @Snippet(path: "CloudRedisCluster_DeleteCluster")
  public func deleteClusterPollingUntilDone(
    request: DeleteClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Creates a Redis cluster based on the specified properties.
  /// The creation is executed asynchronously and callers may check the returned
  /// operation to track its progress. Once the operation is completed the Redis
  /// cluster will be fully functional. The completed longrunning.Operation will
  /// contain the new cluster object in the response field.
  ///
  /// The returned operation is automatically deleted after a few hours, so there
  /// is no need to call DeleteOperation.
  ///
  /// @Snippet(path: "CloudRedisCluster_CreateCluster")
  public func createCluster(
    request: CreateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createCluster(request: request, options: options)
  }

  /// Creates a Redis cluster based on the specified properties.
  /// The creation is executed asynchronously and callers may check the returned
  /// operation to track its progress. Once the operation is completed the Redis
  /// cluster will be fully functional. The completed longrunning.Operation will
  /// contain the new cluster object in the response field.
  ///
  /// The returned operation is automatically deleted after a few hours, so there
  /// is no need to call DeleteOperation.
  ///
  /// @Snippet(path: "CloudRedisCluster_CreateCluster")
  public func createClusterPollingUntilDone(
    request: CreateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      return try op._extractStatus(Cluster.self)
    }
    let rawOp = try await self.createCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets the details of certificate authority information for Redis cluster.
  ///
  /// @Snippet(path: "CloudRedisCluster_GetClusterCertificateAuthority")
  public func getClusterCertificateAuthority(
    request: GetClusterCertificateAuthorityRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.CertificateAuthority {
    try await self.inner.getClusterCertificateAuthority(request: request, options: options)
  }

  /// Gets the details of regional certificate authority information for Redis
  /// cluster.
  ///
  /// @Snippet(path: "CloudRedisCluster_GetSharedRegionalCertificateAuthority")
  public func getSharedRegionalCertificateAuthority(
    request: GetSharedRegionalCertificateAuthorityRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.SharedRegionalCertificateAuthority {
    try await self.inner.getSharedRegionalCertificateAuthority(request: request, options: options)
  }

  /// Reschedules upcoming maintenance event.
  ///
  /// @Snippet(path: "CloudRedisCluster_RescheduleClusterMaintenance")
  public func rescheduleClusterMaintenance(
    request: RescheduleClusterMaintenanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.rescheduleClusterMaintenance(request: request, options: options)
  }

  /// Reschedules upcoming maintenance event.
  ///
  /// @Snippet(path: "CloudRedisCluster_RescheduleClusterMaintenance")
  public func rescheduleClusterMaintenancePollingUntilDone(
    request: RescheduleClusterMaintenanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      return try op._extractStatus(Cluster.self)
    }
    let rawOp = try await self.rescheduleClusterMaintenance(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists all backup collections owned by a consumer project in either the
  /// specified location (region) or all locations.
  ///
  /// If `location_id` is specified as `-` (wildcard), then all regions
  /// available to the project are queried, and the results are aggregated.
  ///
  /// @Snippet(path: "CloudRedisCluster_ListBackupCollections")
  public func listBackupCollections(
    request: ListBackupCollectionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.ListBackupCollectionsResponse {
    try await self.inner.listBackupCollections(request: request, options: options)
  }

  /// Get a backup collection.
  ///
  /// @Snippet(path: "CloudRedisCluster_GetBackupCollection")
  public func getBackupCollection(
    request: GetBackupCollectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.BackupCollection {
    try await self.inner.getBackupCollection(request: request, options: options)
  }

  /// Lists all backups owned by a backup collection.
  ///
  /// @Snippet(path: "CloudRedisCluster_ListBackups")
  public func listBackups(
    request: ListBackupsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.ListBackupsResponse {
    try await self.inner.listBackups(request: request, options: options)
  }

  /// Gets the details of a specific backup.
  ///
  /// @Snippet(path: "CloudRedisCluster_GetBackup")
  public func getBackup(
    request: GetBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.Backup {
    try await self.inner.getBackup(request: request, options: options)
  }

  /// Deletes a specific backup.
  ///
  /// @Snippet(path: "CloudRedisCluster_DeleteBackup")
  public func deleteBackup(
    request: DeleteBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteBackup(request: request, options: options)
  }

  /// Deletes a specific backup.
  ///
  /// @Snippet(path: "CloudRedisCluster_DeleteBackup")
  public func deleteBackupPollingUntilDone(
    request: DeleteBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteBackup(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Exports a specific backup to a customer target Cloud Storage URI.
  ///
  /// @Snippet(path: "CloudRedisCluster_ExportBackup")
  public func exportBackup(
    request: ExportBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.exportBackup(request: request, options: options)
  }

  /// Exports a specific backup to a customer target Cloud Storage URI.
  ///
  /// @Snippet(path: "CloudRedisCluster_ExportBackup")
  public func exportBackupPollingUntilDone(
    request: ExportBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Backup> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Backup>.State in
      return try op._extractStatus(Backup.self)
    }
    let rawOp = try await self.exportBackup(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Backup>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Backup Redis Cluster.
  /// If this is the first time a backup is being created, a backup collection
  /// will be created at the backend, and this backup belongs to this collection.
  /// Both collection and backup will have a resource name. Backup will be
  /// executed for each shard. A replica (primary if nonHA) will be selected to
  /// perform the execution. Backup call will be rejected if there is an ongoing
  /// backup or update operation. Be aware that during preview, if the cluster's
  /// internal software version is too old, critical update will be performed
  /// before actual backup. Once the internal software version is updated to the
  /// minimum version required by the backup feature, subsequent backups will not
  /// require critical update. After preview, there will be no critical update
  /// needed for backup.
  ///
  /// @Snippet(path: "CloudRedisCluster_BackupCluster")
  public func backupCluster(
    request: BackupClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.backupCluster(request: request, options: options)
  }

  /// Backup Redis Cluster.
  /// If this is the first time a backup is being created, a backup collection
  /// will be created at the backend, and this backup belongs to this collection.
  /// Both collection and backup will have a resource name. Backup will be
  /// executed for each shard. A replica (primary if nonHA) will be selected to
  /// perform the execution. Backup call will be rejected if there is an ongoing
  /// backup or update operation. Be aware that during preview, if the cluster's
  /// internal software version is too old, critical update will be performed
  /// before actual backup. Once the internal software version is updated to the
  /// minimum version required by the backup feature, subsequent backups will not
  /// require critical update. After preview, there will be no critical update
  /// needed for backup.
  ///
  /// @Snippet(path: "CloudRedisCluster_BackupCluster")
  public func backupClusterPollingUntilDone(
    request: BackupClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      return try op._extractStatus(Cluster.self)
    }
    let rawOp = try await self.backupCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "CloudRedisCluster_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "CloudRedisCluster_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudRedisCluster_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudRedisCluster_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudRedisCluster_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudRedisCluster_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `CloudRedisClusterClient`.
  ///
  /// To mock `CloudRedisClusterClient` change your functions to receive
  /// `some CloudRedisClusterProtocol` or `any CloudRedisClusterProtocol`
  /// and pass a mock implementation in your tests.
  public protocol CloudRedisClusterProtocol: Sendable {
    /// See `CloudRedisClusterClient.updateCluster`.
    func updateClusterPollingUntilDone(request: UpdateClusterRequest) async throws -> any GoogleGax
      .PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.updateCluster`.
    func updateClusterPollingUntilDone(
      cluster: Cluster?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.deleteCluster`.
    func deleteClusterPollingUntilDone(request: DeleteClusterRequest) async throws -> any GoogleGax
      .PollableOperation<Swift.Void>

    /// See `CloudRedisClusterClient.deleteCluster`.
    func deleteClusterPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `CloudRedisClusterClient.createCluster`.
    func createClusterPollingUntilDone(request: CreateClusterRequest) async throws -> any GoogleGax
      .PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.createCluster`.
    func createClusterPollingUntilDone(
      parent: Swift.String,
      cluster: Cluster?,
      clusterId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.rescheduleClusterMaintenance`.
    func rescheduleClusterMaintenancePollingUntilDone(request: RescheduleClusterMaintenanceRequest)
      async throws -> any GoogleGax.PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.rescheduleClusterMaintenance`.
    func rescheduleClusterMaintenancePollingUntilDone(
      name: Swift.String,
      rescheduleType: RescheduleClusterMaintenanceRequest.RescheduleType,
      scheduleTime: GoogleWKT.WKTTimestamp?,
    ) async throws -> any GoogleGax.PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.deleteBackup`.
    func deleteBackupPollingUntilDone(request: DeleteBackupRequest) async throws -> any GoogleGax
      .PollableOperation<Swift.Void>

    /// See `CloudRedisClusterClient.deleteBackup`.
    func deleteBackupPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `CloudRedisClusterClient.exportBackup`.
    func exportBackupPollingUntilDone(request: ExportBackupRequest) async throws -> any GoogleGax
      .PollableOperation<Backup>

    /// See `CloudRedisClusterClient.backupCluster`.
    func backupClusterPollingUntilDone(request: BackupClusterRequest) async throws -> any GoogleGax
      .PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.backupCluster`.
    func backupClusterPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.listClusters`.
    func listClusters(
      request: ListClustersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.ListClustersResponse

    /// See `CloudRedisClusterClient.getCluster`.
    func getCluster(
      request: GetClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.Cluster

    /// See `CloudRedisClusterClient.updateCluster`.
    func updateCluster(
      request: UpdateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.updateCluster`.
    func updateClusterPollingUntilDone(
      request: UpdateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.deleteCluster`.
    func deleteCluster(
      request: DeleteClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.deleteCluster`.
    func deleteClusterPollingUntilDone(
      request: DeleteClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `CloudRedisClusterClient.createCluster`.
    func createCluster(
      request: CreateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.createCluster`.
    func createClusterPollingUntilDone(
      request: CreateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.getClusterCertificateAuthority`.
    func getClusterCertificateAuthority(
      request: GetClusterCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.CertificateAuthority

    /// See `CloudRedisClusterClient.getSharedRegionalCertificateAuthority`.
    func getSharedRegionalCertificateAuthority(
      request: GetSharedRegionalCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.SharedRegionalCertificateAuthority

    /// See `CloudRedisClusterClient.rescheduleClusterMaintenance`.
    func rescheduleClusterMaintenance(
      request: RescheduleClusterMaintenanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.rescheduleClusterMaintenance`.
    func rescheduleClusterMaintenancePollingUntilDone(
      request: RescheduleClusterMaintenanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.listBackupCollections`.
    func listBackupCollections(
      request: ListBackupCollectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.ListBackupCollectionsResponse

    /// See `CloudRedisClusterClient.getBackupCollection`.
    func getBackupCollection(
      request: GetBackupCollectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.BackupCollection

    /// See `CloudRedisClusterClient.listBackups`.
    func listBackups(
      request: ListBackupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.ListBackupsResponse

    /// See `CloudRedisClusterClient.getBackup`.
    func getBackup(
      request: GetBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.Backup

    /// See `CloudRedisClusterClient.deleteBackup`.
    func deleteBackup(
      request: DeleteBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.deleteBackup`.
    func deleteBackupPollingUntilDone(
      request: DeleteBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `CloudRedisClusterClient.exportBackup`.
    func exportBackup(
      request: ExportBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.exportBackup`.
    func exportBackupPollingUntilDone(
      request: ExportBackupRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Backup>

    /// See `CloudRedisClusterClient.backupCluster`.
    func backupCluster(
      request: BackupClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.backupCluster`.
    func backupClusterPollingUntilDone(
      request: BackupClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `CloudRedisClusterClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `CloudRedisClusterClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `CloudRedisClusterClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `CloudRedisClusterClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.CloudRedisClusterProtocol {
  public func listClusters(request: ListClustersRequest) async throws
    -> GoogleCloudRedisClusterV1.ListClustersResponse
  {
    try await self.listClusters(request: request, options: .init())
  }

  public func listClusters(
    request: ListClustersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.ListClustersResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listClustersByItems(
    request: ListClustersRequest
  ) -> any AsyncSequence<Cluster, Swift.Error> & Sendable {
    self.listClustersByItems(request: request, options: .init())
  }

  /// Lists all Redis clusters owned by a project in either the specified
  /// location (region) or all locations.
  ///
  /// The location should have the following format:
  ///
  /// * `projects/{project_id}/locations/{location_id}`
  ///
  /// If `location_id` is specified as `-` (wildcard), then all regions
  /// available to the project are queried, and the results are aggregated.
  ///
  /// @Snippet(path: "CloudRedisCluster_ListClusters")
  public func listClustersByItems(
    request: ListClustersRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Cluster, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudRedisClusterV1.ListClustersResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listClusters(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listClustersByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Cluster, Swift.Error> & Sendable {
    let request = ListClustersRequest().with {
      $0.parent = parent
    }
    return self.listClustersByItems(request: request)
  }

  public func getCluster(request: GetClusterRequest) async throws
    -> GoogleCloudRedisClusterV1.Cluster
  {
    try await self.getCluster(request: request, options: .init())
  }

  public func getCluster(
    request: GetClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.Cluster {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getCluster(
    name: Swift.String,
  ) async throws -> GoogleCloudRedisClusterV1.Cluster {
    let request = GetClusterRequest().with {
      $0.name = name
    }
    return try await self.getCluster(request: request)
  }

  public func updateCluster(request: UpdateClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateCluster(request: request, options: .init())
  }

  public func updateCluster(
    request: UpdateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateClusterPollingUntilDone(request: UpdateClusterRequest) async throws
    -> any GoogleGax.PollableOperation<Cluster>
  {
    try await self.updateClusterPollingUntilDone(request: request, options: .init())
  }

  public func updateClusterPollingUntilDone(
    request: UpdateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateClusterPollingUntilDone(
    cluster: Cluster?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let request = UpdateClusterRequest().with {
      $0.cluster = cluster
      $0.updateMask = updateMask
    }
    return try await self.updateClusterPollingUntilDone(request: request)
  }

  public func deleteCluster(request: DeleteClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteCluster(request: request, options: .init())
  }

  public func deleteCluster(
    request: DeleteClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteClusterPollingUntilDone(request: DeleteClusterRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteClusterPollingUntilDone(request: request, options: .init())
  }

  public func deleteClusterPollingUntilDone(
    request: DeleteClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteClusterPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteClusterRequest().with {
      $0.name = name
    }
    return try await self.deleteClusterPollingUntilDone(request: request)
  }

  public func createCluster(request: CreateClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createCluster(request: request, options: .init())
  }

  public func createCluster(
    request: CreateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createClusterPollingUntilDone(request: CreateClusterRequest) async throws
    -> any GoogleGax.PollableOperation<Cluster>
  {
    try await self.createClusterPollingUntilDone(request: request, options: .init())
  }

  public func createClusterPollingUntilDone(
    request: CreateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createClusterPollingUntilDone(
    parent: Swift.String,
    cluster: Cluster?,
    clusterId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let request = CreateClusterRequest().with {
      $0.parent = parent
      $0.cluster = cluster
      $0.clusterId = clusterId
    }
    return try await self.createClusterPollingUntilDone(request: request)
  }

  public func getClusterCertificateAuthority(request: GetClusterCertificateAuthorityRequest)
    async throws -> GoogleCloudRedisClusterV1.CertificateAuthority
  {
    try await self.getClusterCertificateAuthority(request: request, options: .init())
  }

  public func getClusterCertificateAuthority(
    request: GetClusterCertificateAuthorityRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.CertificateAuthority {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getClusterCertificateAuthority(
    name: Swift.String,
  ) async throws -> GoogleCloudRedisClusterV1.CertificateAuthority {
    let request = GetClusterCertificateAuthorityRequest().with {
      $0.name = name
    }
    return try await self.getClusterCertificateAuthority(request: request)
  }

  public func getSharedRegionalCertificateAuthority(
    request: GetSharedRegionalCertificateAuthorityRequest
  ) async throws -> GoogleCloudRedisClusterV1.SharedRegionalCertificateAuthority {
    try await self.getSharedRegionalCertificateAuthority(request: request, options: .init())
  }

  public func getSharedRegionalCertificateAuthority(
    request: GetSharedRegionalCertificateAuthorityRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.SharedRegionalCertificateAuthority {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getSharedRegionalCertificateAuthority(
    name: Swift.String,
  ) async throws -> GoogleCloudRedisClusterV1.SharedRegionalCertificateAuthority {
    let request = GetSharedRegionalCertificateAuthorityRequest().with {
      $0.name = name
    }
    return try await self.getSharedRegionalCertificateAuthority(request: request)
  }

  public func rescheduleClusterMaintenance(request: RescheduleClusterMaintenanceRequest)
    async throws -> GoogleLongRunning.Operation
  {
    try await self.rescheduleClusterMaintenance(request: request, options: .init())
  }

  public func rescheduleClusterMaintenance(
    request: RescheduleClusterMaintenanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func rescheduleClusterMaintenancePollingUntilDone(
    request: RescheduleClusterMaintenanceRequest
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    try await self.rescheduleClusterMaintenancePollingUntilDone(request: request, options: .init())
  }

  public func rescheduleClusterMaintenancePollingUntilDone(
    request: RescheduleClusterMaintenanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func rescheduleClusterMaintenancePollingUntilDone(
    name: Swift.String,
    rescheduleType: RescheduleClusterMaintenanceRequest.RescheduleType,
    scheduleTime: GoogleWKT.WKTTimestamp?,
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let request = RescheduleClusterMaintenanceRequest().with {
      $0.name = name
      $0.rescheduleType = rescheduleType
      $0.scheduleTime = scheduleTime
    }
    return try await self.rescheduleClusterMaintenancePollingUntilDone(request: request)
  }

  public func listBackupCollections(request: ListBackupCollectionsRequest) async throws
    -> GoogleCloudRedisClusterV1.ListBackupCollectionsResponse
  {
    try await self.listBackupCollections(request: request, options: .init())
  }

  public func listBackupCollections(
    request: ListBackupCollectionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.ListBackupCollectionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listBackupCollectionsByItems(
    request: ListBackupCollectionsRequest
  ) -> any AsyncSequence<BackupCollection, Swift.Error> & Sendable {
    self.listBackupCollectionsByItems(request: request, options: .init())
  }

  /// Lists all backup collections owned by a consumer project in either the
  /// specified location (region) or all locations.
  ///
  /// If `location_id` is specified as `-` (wildcard), then all regions
  /// available to the project are queried, and the results are aggregated.
  ///
  /// @Snippet(path: "CloudRedisCluster_ListBackupCollections")
  public func listBackupCollectionsByItems(
    request: ListBackupCollectionsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<BackupCollection, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudRedisClusterV1.ListBackupCollectionsResponse in
      var request = request
      request.pageToken = token
      return try await self.listBackupCollections(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listBackupCollectionsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<BackupCollection, Swift.Error> & Sendable {
    let request = ListBackupCollectionsRequest().with {
      $0.parent = parent
    }
    return self.listBackupCollectionsByItems(request: request)
  }

  public func getBackupCollection(request: GetBackupCollectionRequest) async throws
    -> GoogleCloudRedisClusterV1.BackupCollection
  {
    try await self.getBackupCollection(request: request, options: .init())
  }

  public func getBackupCollection(
    request: GetBackupCollectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.BackupCollection {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getBackupCollection(
    name: Swift.String,
  ) async throws -> GoogleCloudRedisClusterV1.BackupCollection {
    let request = GetBackupCollectionRequest().with {
      $0.name = name
    }
    return try await self.getBackupCollection(request: request)
  }

  public func listBackups(request: ListBackupsRequest) async throws
    -> GoogleCloudRedisClusterV1.ListBackupsResponse
  {
    try await self.listBackups(request: request, options: .init())
  }

  public func listBackups(
    request: ListBackupsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.ListBackupsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listBackupsByItems(
    request: ListBackupsRequest
  ) -> any AsyncSequence<Backup, Swift.Error> & Sendable {
    self.listBackupsByItems(request: request, options: .init())
  }

  /// Lists all backups owned by a backup collection.
  ///
  /// @Snippet(path: "CloudRedisCluster_ListBackups")
  public func listBackupsByItems(
    request: ListBackupsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Backup, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudRedisClusterV1.ListBackupsResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listBackups(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listBackupsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Backup, Swift.Error> & Sendable {
    let request = ListBackupsRequest().with {
      $0.parent = parent
    }
    return self.listBackupsByItems(request: request)
  }

  public func getBackup(request: GetBackupRequest) async throws -> GoogleCloudRedisClusterV1.Backup
  {
    try await self.getBackup(request: request, options: .init())
  }

  public func getBackup(
    request: GetBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.Backup {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getBackup(
    name: Swift.String,
  ) async throws -> GoogleCloudRedisClusterV1.Backup {
    let request = GetBackupRequest().with {
      $0.name = name
    }
    return try await self.getBackup(request: request)
  }

  public func deleteBackup(request: DeleteBackupRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.deleteBackup(request: request, options: .init())
  }

  public func deleteBackup(
    request: DeleteBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteBackupPollingUntilDone(request: DeleteBackupRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteBackupPollingUntilDone(request: request, options: .init())
  }

  public func deleteBackupPollingUntilDone(
    request: DeleteBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteBackupPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteBackupRequest().with {
      $0.name = name
    }
    return try await self.deleteBackupPollingUntilDone(request: request)
  }

  public func exportBackup(request: ExportBackupRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.exportBackup(request: request, options: .init())
  }

  public func exportBackup(
    request: ExportBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func exportBackupPollingUntilDone(request: ExportBackupRequest) async throws
    -> any GoogleGax.PollableOperation<Backup>
  {
    try await self.exportBackupPollingUntilDone(request: request, options: .init())
  }

  public func exportBackupPollingUntilDone(
    request: ExportBackupRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Backup> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Backup>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func backupCluster(request: BackupClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.backupCluster(request: request, options: .init())
  }

  public func backupCluster(
    request: BackupClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func backupClusterPollingUntilDone(request: BackupClusterRequest) async throws
    -> any GoogleGax.PollableOperation<Cluster>
  {
    try await self.backupClusterPollingUntilDone(request: request, options: .init())
  }

  public func backupClusterPollingUntilDone(
    request: BackupClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func backupClusterPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let request = BackupClusterRequest().with {
      $0.name = name
    }
    return try await self.backupClusterPollingUntilDone(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "CloudRedisCluster_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudRedisCluster_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
