// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Configures and manages Cloud Memorystore for Redis clusters
///
/// Google Cloud Memorystore for Redis Cluster
///
/// The `redis.googleapis.com` service implements the Google Cloud Memorystore
/// for Redis API and defines the following resource model for managing Redis
/// clusters:
/// * The service works with a collection of cloud projects, named: `/projects/*`
/// * Each project has a collection of available locations, named: `/locations/*`
/// * Each location has a collection of Redis clusters, named: `/clusters/*`
/// * As such, Redis clusters are resources of the form:
///   `/projects/{project_id}/locations/{location_id}/clusters/{instance_id}`
///
/// Note that location_id must be a GCP `region`; for example:
/// * `projects/redpepper-1290/locations/us-central1/clusters/my-redis`
///
/// @Snippet(path: "CloudRedisClusterQuickstart")
public final class CloudRedisClusterClient: Clients.CloudRedisClusterProtocol, Sendable {
  let inner: any Clients.CloudRedisClusterStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `CloudRedisClusterClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.CloudRedisClusterStub = try Clients.CloudRedisClusterTransport(options)
    inner = Clients.CloudRedisClusterRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.CloudRedisClusterLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists all Redis clusters owned by a project in either the specified
  /// location (region) or all locations.
  ///
  /// The location should have the following format:
  ///
  /// * `projects/{project_id}/locations/{location_id}`
  ///
  /// If `location_id` is specified as `-` (wildcard), then all regions
  /// available to the project are queried, and the results are aggregated.
  ///
  /// @Snippet(path: "CloudRedisCluster_ListClusters")
  public func listClusters(
    request: ListClustersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.ListClustersResponse {
    try await self.inner.listClusters(request: request, options: options)
  }

  /// Lists all Redis clusters owned by a project in either the specified
  /// location (region) or all locations.
  ///
  /// The location should have the following format:
  ///
  /// * `projects/{project_id}/locations/{location_id}`
  ///
  /// If `location_id` is specified as `-` (wildcard), then all regions
  /// available to the project are queried, and the results are aggregated.
  ///
  /// @Snippet(path: "CloudRedisCluster_ListClusters")
  public func listClusters(
    byItem: ListClustersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Cluster, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudRedisClusterV1.ListClustersResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listClusters(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets the details of a specific Redis cluster.
  ///
  /// @Snippet(path: "CloudRedisCluster_GetCluster")
  public func getCluster(
    request: GetClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.Cluster {
    try await self.inner.getCluster(request: request, options: options)
  }

  /// Updates the metadata and configuration of a specific Redis cluster.
  ///
  /// Completed longrunning.Operation will contain the new cluster object
  /// in the response field. The returned operation is automatically deleted
  /// after a few hours, so there is no need to call DeleteOperation.
  ///
  /// @Snippet(path: "CloudRedisCluster_UpdateCluster")
  public func updateCluster(
    request: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateCluster(request: request, options: options)
  }

  /// Updates the metadata and configuration of a specific Redis cluster.
  ///
  /// Completed longrunning.Operation will contain the new cluster object
  /// in the response field. The returned operation is automatically deleted
  /// after a few hours, so there is no need to call DeleteOperation.
  ///
  /// @Snippet(path: "CloudRedisCluster_UpdateCluster")
  public func updateCluster(
    withPolling: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      return try op._extractStatus(Cluster.self)
    }
    let rawOp = try await self.updateCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a specific Redis cluster. Cluster stops serving and data is
  /// deleted.
  ///
  /// @Snippet(path: "CloudRedisCluster_DeleteCluster")
  public func deleteCluster(
    request: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteCluster(request: request, options: options)
  }

  /// Deletes a specific Redis cluster. Cluster stops serving and data is
  /// deleted.
  ///
  /// @Snippet(path: "CloudRedisCluster_DeleteCluster")
  public func deleteCluster(
    withPolling: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Creates a Redis cluster based on the specified properties.
  /// The creation is executed asynchronously and callers may check the returned
  /// operation to track its progress. Once the operation is completed the Redis
  /// cluster will be fully functional. The completed longrunning.Operation will
  /// contain the new cluster object in the response field.
  ///
  /// The returned operation is automatically deleted after a few hours, so there
  /// is no need to call DeleteOperation.
  ///
  /// @Snippet(path: "CloudRedisCluster_CreateCluster")
  public func createCluster(
    request: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createCluster(request: request, options: options)
  }

  /// Creates a Redis cluster based on the specified properties.
  /// The creation is executed asynchronously and callers may check the returned
  /// operation to track its progress. Once the operation is completed the Redis
  /// cluster will be fully functional. The completed longrunning.Operation will
  /// contain the new cluster object in the response field.
  ///
  /// The returned operation is automatically deleted after a few hours, so there
  /// is no need to call DeleteOperation.
  ///
  /// @Snippet(path: "CloudRedisCluster_CreateCluster")
  public func createCluster(
    withPolling: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      return try op._extractStatus(Cluster.self)
    }
    let rawOp = try await self.createCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets the details of certificate authority information for Redis cluster.
  ///
  /// @Snippet(path: "CloudRedisCluster_GetClusterCertificateAuthority")
  public func getClusterCertificateAuthority(
    request: GetClusterCertificateAuthorityRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.CertificateAuthority {
    try await self.inner.getClusterCertificateAuthority(request: request, options: options)
  }

  /// Gets the details of regional certificate authority information for Redis
  /// cluster.
  ///
  /// @Snippet(path: "CloudRedisCluster_GetSharedRegionalCertificateAuthority")
  public func getSharedRegionalCertificateAuthority(
    request: GetSharedRegionalCertificateAuthorityRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.SharedRegionalCertificateAuthority {
    try await self.inner.getSharedRegionalCertificateAuthority(request: request, options: options)
  }

  /// Reschedules upcoming maintenance event.
  ///
  /// @Snippet(path: "CloudRedisCluster_RescheduleClusterMaintenance")
  public func rescheduleClusterMaintenance(
    request: RescheduleClusterMaintenanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.rescheduleClusterMaintenance(request: request, options: options)
  }

  /// Reschedules upcoming maintenance event.
  ///
  /// @Snippet(path: "CloudRedisCluster_RescheduleClusterMaintenance")
  public func rescheduleClusterMaintenance(
    withPolling: RescheduleClusterMaintenanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      return try op._extractStatus(Cluster.self)
    }
    let rawOp = try await self.rescheduleClusterMaintenance(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists all backup collections owned by a consumer project in either the
  /// specified location (region) or all locations.
  ///
  /// If `location_id` is specified as `-` (wildcard), then all regions
  /// available to the project are queried, and the results are aggregated.
  ///
  /// @Snippet(path: "CloudRedisCluster_ListBackupCollections")
  public func listBackupCollections(
    request: ListBackupCollectionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.ListBackupCollectionsResponse {
    try await self.inner.listBackupCollections(request: request, options: options)
  }

  /// Lists all backup collections owned by a consumer project in either the
  /// specified location (region) or all locations.
  ///
  /// If `location_id` is specified as `-` (wildcard), then all regions
  /// available to the project are queried, and the results are aggregated.
  ///
  /// @Snippet(path: "CloudRedisCluster_ListBackupCollections")
  public func listBackupCollections(
    byItem: ListBackupCollectionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<BackupCollection, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudRedisClusterV1.ListBackupCollectionsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listBackupCollections(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Get a backup collection.
  ///
  /// @Snippet(path: "CloudRedisCluster_GetBackupCollection")
  public func getBackupCollection(
    request: GetBackupCollectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.BackupCollection {
    try await self.inner.getBackupCollection(request: request, options: options)
  }

  /// Lists all backups owned by a backup collection.
  ///
  /// @Snippet(path: "CloudRedisCluster_ListBackups")
  public func listBackups(
    request: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.ListBackupsResponse {
    try await self.inner.listBackups(request: request, options: options)
  }

  /// Lists all backups owned by a backup collection.
  ///
  /// @Snippet(path: "CloudRedisCluster_ListBackups")
  public func listBackups(
    byItem: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Backup, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudRedisClusterV1.ListBackupsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listBackups(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets the details of a specific backup.
  ///
  /// @Snippet(path: "CloudRedisCluster_GetBackup")
  public func getBackup(
    request: GetBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.Backup {
    try await self.inner.getBackup(request: request, options: options)
  }

  /// Deletes a specific backup.
  ///
  /// @Snippet(path: "CloudRedisCluster_DeleteBackup")
  public func deleteBackup(
    request: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteBackup(request: request, options: options)
  }

  /// Deletes a specific backup.
  ///
  /// @Snippet(path: "CloudRedisCluster_DeleteBackup")
  public func deleteBackup(
    withPolling: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteBackup(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Exports a specific backup to a customer target Cloud Storage URI.
  ///
  /// @Snippet(path: "CloudRedisCluster_ExportBackup")
  public func exportBackup(
    request: ExportBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.exportBackup(request: request, options: options)
  }

  /// Exports a specific backup to a customer target Cloud Storage URI.
  ///
  /// @Snippet(path: "CloudRedisCluster_ExportBackup")
  public func exportBackup(
    withPolling: ExportBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Backup> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Backup>.State in
      return try op._extractStatus(Backup.self)
    }
    let rawOp = try await self.exportBackup(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Backup>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Backup Redis Cluster.
  /// If this is the first time a backup is being created, a backup collection
  /// will be created at the backend, and this backup belongs to this collection.
  /// Both collection and backup will have a resource name. Backup will be
  /// executed for each shard. A replica (primary if nonHA) will be selected to
  /// perform the execution. Backup call will be rejected if there is an ongoing
  /// backup or update operation. Be aware that during preview, if the cluster's
  /// internal software version is too old, critical update will be performed
  /// before actual backup. Once the internal software version is updated to the
  /// minimum version required by the backup feature, subsequent backups will not
  /// require critical update. After preview, there will be no critical update
  /// needed for backup.
  ///
  /// @Snippet(path: "CloudRedisCluster_BackupCluster")
  public func backupCluster(
    request: BackupClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.backupCluster(request: request, options: options)
  }

  /// Backup Redis Cluster.
  /// If this is the first time a backup is being created, a backup collection
  /// will be created at the backend, and this backup belongs to this collection.
  /// Both collection and backup will have a resource name. Backup will be
  /// executed for each shard. A replica (primary if nonHA) will be selected to
  /// perform the execution. Backup call will be rejected if there is an ongoing
  /// backup or update operation. Be aware that during preview, if the cluster's
  /// internal software version is too old, critical update will be performed
  /// before actual backup. Once the internal software version is updated to the
  /// minimum version required by the backup feature, subsequent backups will not
  /// require critical update. After preview, there will be no critical update
  /// needed for backup.
  ///
  /// @Snippet(path: "CloudRedisCluster_BackupCluster")
  public func backupCluster(
    withPolling: BackupClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      return try op._extractStatus(Cluster.self)
    }
    let rawOp = try await self.backupCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "CloudRedisCluster_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "CloudRedisCluster_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "CloudRedisCluster_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudRedisCluster_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudRedisCluster_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudRedisCluster_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudRedisCluster_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CloudRedisCluster_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `CloudRedisClusterClient`.
  ///
  /// To mock `CloudRedisClusterClient` change your functions to receive
  /// `some CloudRedisClusterProtocol` or `any CloudRedisClusterProtocol`
  /// and pass a mock implementation in your tests.
  public protocol CloudRedisClusterProtocol {
    /// See `CloudRedisClusterClient.listClusters`.
    func listClusters(request: ListClustersRequest) async throws
      -> GoogleCloudRedisClusterV1.ListClustersResponse

    /// See `CloudRedisClusterClient.listClusters`.
    func listClusters(
      byItem: ListClustersRequest
    ) throws -> any AsyncSequence<Cluster, Swift.Error>

    /// See `CloudRedisClusterClient.listClusters`.
    func listClusters(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Cluster, Swift.Error>

    /// See `CloudRedisClusterClient.getCluster`.
    func getCluster(request: GetClusterRequest) async throws -> GoogleCloudRedisClusterV1.Cluster

    /// See `CloudRedisClusterClient.getCluster`.
    func getCluster(
      name: Swift.String,
    ) async throws -> GoogleCloudRedisClusterV1.Cluster

    /// See `CloudRedisClusterClient.updateCluster`.
    func updateCluster(request: UpdateClusterRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.updateCluster`.
    func updateCluster(withPolling: UpdateClusterRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.updateCluster`.
    func updateCluster(
      cluster: Cluster?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.deleteCluster`.
    func deleteCluster(request: DeleteClusterRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.deleteCluster`.
    func deleteCluster(withPolling: DeleteClusterRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `CloudRedisClusterClient.deleteCluster`.
    func deleteCluster(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `CloudRedisClusterClient.createCluster`.
    func createCluster(request: CreateClusterRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.createCluster`.
    func createCluster(withPolling: CreateClusterRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.createCluster`.
    func createCluster(
      parent: Swift.String,
      cluster: Cluster?,
      clusterId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.getClusterCertificateAuthority`.
    func getClusterCertificateAuthority(request: GetClusterCertificateAuthorityRequest) async throws
      -> GoogleCloudRedisClusterV1.CertificateAuthority

    /// See `CloudRedisClusterClient.getClusterCertificateAuthority`.
    func getClusterCertificateAuthority(
      name: Swift.String,
    ) async throws -> GoogleCloudRedisClusterV1.CertificateAuthority

    /// See `CloudRedisClusterClient.getSharedRegionalCertificateAuthority`.
    func getSharedRegionalCertificateAuthority(
      request: GetSharedRegionalCertificateAuthorityRequest
    ) async throws -> GoogleCloudRedisClusterV1.SharedRegionalCertificateAuthority

    /// See `CloudRedisClusterClient.getSharedRegionalCertificateAuthority`.
    func getSharedRegionalCertificateAuthority(
      name: Swift.String,
    ) async throws -> GoogleCloudRedisClusterV1.SharedRegionalCertificateAuthority

    /// See `CloudRedisClusterClient.rescheduleClusterMaintenance`.
    func rescheduleClusterMaintenance(request: RescheduleClusterMaintenanceRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.rescheduleClusterMaintenance`.
    func rescheduleClusterMaintenance(withPolling: RescheduleClusterMaintenanceRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.rescheduleClusterMaintenance`.
    func rescheduleClusterMaintenance(
      name: Swift.String,
      rescheduleType: RescheduleClusterMaintenanceRequest.RescheduleType,
      scheduleTime: GoogleCloudWKT.Timestamp?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.listBackupCollections`.
    func listBackupCollections(request: ListBackupCollectionsRequest) async throws
      -> GoogleCloudRedisClusterV1.ListBackupCollectionsResponse

    /// See `CloudRedisClusterClient.listBackupCollections`.
    func listBackupCollections(
      byItem: ListBackupCollectionsRequest
    ) throws -> any AsyncSequence<BackupCollection, Swift.Error>

    /// See `CloudRedisClusterClient.listBackupCollections`.
    func listBackupCollections(
      parent: Swift.String,
    ) throws -> any AsyncSequence<BackupCollection, Swift.Error>

    /// See `CloudRedisClusterClient.getBackupCollection`.
    func getBackupCollection(request: GetBackupCollectionRequest) async throws
      -> GoogleCloudRedisClusterV1.BackupCollection

    /// See `CloudRedisClusterClient.getBackupCollection`.
    func getBackupCollection(
      name: Swift.String,
    ) async throws -> GoogleCloudRedisClusterV1.BackupCollection

    /// See `CloudRedisClusterClient.listBackups`.
    func listBackups(request: ListBackupsRequest) async throws
      -> GoogleCloudRedisClusterV1.ListBackupsResponse

    /// See `CloudRedisClusterClient.listBackups`.
    func listBackups(
      byItem: ListBackupsRequest
    ) throws -> any AsyncSequence<Backup, Swift.Error>

    /// See `CloudRedisClusterClient.listBackups`.
    func listBackups(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Backup, Swift.Error>

    /// See `CloudRedisClusterClient.getBackup`.
    func getBackup(request: GetBackupRequest) async throws -> GoogleCloudRedisClusterV1.Backup

    /// See `CloudRedisClusterClient.getBackup`.
    func getBackup(
      name: Swift.String,
    ) async throws -> GoogleCloudRedisClusterV1.Backup

    /// See `CloudRedisClusterClient.deleteBackup`.
    func deleteBackup(request: DeleteBackupRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.deleteBackup`.
    func deleteBackup(withPolling: DeleteBackupRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `CloudRedisClusterClient.deleteBackup`.
    func deleteBackup(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `CloudRedisClusterClient.exportBackup`.
    func exportBackup(request: ExportBackupRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.exportBackup`.
    func exportBackup(withPolling: ExportBackupRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Backup>

    /// See `CloudRedisClusterClient.backupCluster`.
    func backupCluster(request: BackupClusterRequest) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.backupCluster`.
    func backupCluster(withPolling: BackupClusterRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.backupCluster`.
    func backupCluster(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `CloudRedisClusterClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `CloudRedisClusterClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `CloudRedisClusterClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `CloudRedisClusterClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `CloudRedisClusterClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `CloudRedisClusterClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `CloudRedisClusterClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `CloudRedisClusterClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `CloudRedisClusterClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `CloudRedisClusterClient.listClusters`.
    func listClusters(
      request: ListClustersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.ListClustersResponse

    /// See `CloudRedisClusterClient.listClusters`.
    func listClusters(
      byItem: ListClustersRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Cluster, Swift.Error>

    /// See `CloudRedisClusterClient.getCluster`.
    func getCluster(
      request: GetClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.Cluster

    /// See `CloudRedisClusterClient.updateCluster`.
    func updateCluster(
      request: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.updateCluster`.
    func updateCluster(
      withPolling: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.deleteCluster`.
    func deleteCluster(
      request: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.deleteCluster`.
    func deleteCluster(
      withPolling: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `CloudRedisClusterClient.createCluster`.
    func createCluster(
      request: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.createCluster`.
    func createCluster(
      withPolling: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.getClusterCertificateAuthority`.
    func getClusterCertificateAuthority(
      request: GetClusterCertificateAuthorityRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.CertificateAuthority

    /// See `CloudRedisClusterClient.getSharedRegionalCertificateAuthority`.
    func getSharedRegionalCertificateAuthority(
      request: GetSharedRegionalCertificateAuthorityRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.SharedRegionalCertificateAuthority

    /// See `CloudRedisClusterClient.rescheduleClusterMaintenance`.
    func rescheduleClusterMaintenance(
      request: RescheduleClusterMaintenanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.rescheduleClusterMaintenance`.
    func rescheduleClusterMaintenance(
      withPolling: RescheduleClusterMaintenanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.listBackupCollections`.
    func listBackupCollections(
      request: ListBackupCollectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.ListBackupCollectionsResponse

    /// See `CloudRedisClusterClient.listBackupCollections`.
    func listBackupCollections(
      byItem: ListBackupCollectionsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<BackupCollection, Swift.Error>

    /// See `CloudRedisClusterClient.getBackupCollection`.
    func getBackupCollection(
      request: GetBackupCollectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.BackupCollection

    /// See `CloudRedisClusterClient.listBackups`.
    func listBackups(
      request: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.ListBackupsResponse

    /// See `CloudRedisClusterClient.listBackups`.
    func listBackups(
      byItem: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Backup, Swift.Error>

    /// See `CloudRedisClusterClient.getBackup`.
    func getBackup(
      request: GetBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.Backup

    /// See `CloudRedisClusterClient.deleteBackup`.
    func deleteBackup(
      request: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.deleteBackup`.
    func deleteBackup(
      withPolling: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `CloudRedisClusterClient.exportBackup`.
    func exportBackup(
      request: ExportBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.exportBackup`.
    func exportBackup(
      withPolling: ExportBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Backup>

    /// See `CloudRedisClusterClient.backupCluster`.
    func backupCluster(
      request: BackupClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `CloudRedisClusterClient.backupCluster`.
    func backupCluster(
      withPolling: BackupClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Cluster>

    /// See `CloudRedisClusterClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `CloudRedisClusterClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `CloudRedisClusterClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `CloudRedisClusterClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `CloudRedisClusterClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `CloudRedisClusterClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `CloudRedisClusterClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.CloudRedisClusterProtocol {
  public func listClusters(request: ListClustersRequest) async throws
    -> GoogleCloudRedisClusterV1.ListClustersResponse
  {
    try await self.listClusters(request: request, options: .init())
  }

  public func listClusters(
    request: ListClustersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.ListClustersResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listClusters(
    byItem: ListClustersRequest
  ) throws -> any AsyncSequence<Cluster, Swift.Error> {
    try self.listClusters(byItem: byItem, options: .init())
  }

  public func listClusters(
    byItem: ListClustersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Cluster, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudRedisClusterV1.ListClustersResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listClusters(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Cluster, Swift.Error> {
    let request = ListClustersRequest().with {
      $0.parent = parent
    }
    return try self.listClusters(byItem: request)
  }

  public func getCluster(request: GetClusterRequest) async throws
    -> GoogleCloudRedisClusterV1.Cluster
  {
    try await self.getCluster(request: request, options: .init())
  }

  public func getCluster(
    request: GetClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.Cluster {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getCluster(
    name: Swift.String,
  ) async throws -> GoogleCloudRedisClusterV1.Cluster {
    let request = GetClusterRequest().with {
      $0.name = name
    }
    return try await self.getCluster(request: request)
  }

  public func updateCluster(request: UpdateClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateCluster(request: request, options: .init())
  }

  public func updateCluster(
    request: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateCluster(withPolling: UpdateClusterRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Cluster>
  {
    try await self.updateCluster(withPolling: withPolling, options: .init())
  }

  public func updateCluster(
    withPolling: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateCluster(
    cluster: Cluster?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let request = UpdateClusterRequest().with {
      $0.cluster = cluster
      $0.updateMask = updateMask
    }
    return try await self.updateCluster(withPolling: request)
  }

  public func deleteCluster(request: DeleteClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteCluster(request: request, options: .init())
  }

  public func deleteCluster(
    request: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteCluster(withPolling: DeleteClusterRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteCluster(withPolling: withPolling, options: .init())
  }

  public func deleteCluster(
    withPolling: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteCluster(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteClusterRequest().with {
      $0.name = name
    }
    return try await self.deleteCluster(withPolling: request)
  }

  public func createCluster(request: CreateClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createCluster(request: request, options: .init())
  }

  public func createCluster(
    request: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createCluster(withPolling: CreateClusterRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Cluster>
  {
    try await self.createCluster(withPolling: withPolling, options: .init())
  }

  public func createCluster(
    withPolling: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createCluster(
    parent: Swift.String,
    cluster: Cluster?,
    clusterId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let request = CreateClusterRequest().with {
      $0.parent = parent
      $0.cluster = cluster
      $0.clusterId = clusterId
    }
    return try await self.createCluster(withPolling: request)
  }

  public func getClusterCertificateAuthority(request: GetClusterCertificateAuthorityRequest)
    async throws -> GoogleCloudRedisClusterV1.CertificateAuthority
  {
    try await self.getClusterCertificateAuthority(request: request, options: .init())
  }

  public func getClusterCertificateAuthority(
    request: GetClusterCertificateAuthorityRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.CertificateAuthority {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getClusterCertificateAuthority(
    name: Swift.String,
  ) async throws -> GoogleCloudRedisClusterV1.CertificateAuthority {
    let request = GetClusterCertificateAuthorityRequest().with {
      $0.name = name
    }
    return try await self.getClusterCertificateAuthority(request: request)
  }

  public func getSharedRegionalCertificateAuthority(
    request: GetSharedRegionalCertificateAuthorityRequest
  ) async throws -> GoogleCloudRedisClusterV1.SharedRegionalCertificateAuthority {
    try await self.getSharedRegionalCertificateAuthority(request: request, options: .init())
  }

  public func getSharedRegionalCertificateAuthority(
    request: GetSharedRegionalCertificateAuthorityRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.SharedRegionalCertificateAuthority {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getSharedRegionalCertificateAuthority(
    name: Swift.String,
  ) async throws -> GoogleCloudRedisClusterV1.SharedRegionalCertificateAuthority {
    let request = GetSharedRegionalCertificateAuthorityRequest().with {
      $0.name = name
    }
    return try await self.getSharedRegionalCertificateAuthority(request: request)
  }

  public func rescheduleClusterMaintenance(request: RescheduleClusterMaintenanceRequest)
    async throws -> GoogleLongRunning.Operation
  {
    try await self.rescheduleClusterMaintenance(request: request, options: .init())
  }

  public func rescheduleClusterMaintenance(
    request: RescheduleClusterMaintenanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func rescheduleClusterMaintenance(withPolling: RescheduleClusterMaintenanceRequest)
    async throws -> any GoogleCloudGax.PollableOperation<Cluster>
  {
    try await self.rescheduleClusterMaintenance(withPolling: withPolling, options: .init())
  }

  public func rescheduleClusterMaintenance(
    withPolling: RescheduleClusterMaintenanceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func rescheduleClusterMaintenance(
    name: Swift.String,
    rescheduleType: RescheduleClusterMaintenanceRequest.RescheduleType,
    scheduleTime: GoogleCloudWKT.Timestamp?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let request = RescheduleClusterMaintenanceRequest().with {
      $0.name = name
      $0.rescheduleType = rescheduleType
      $0.scheduleTime = scheduleTime
    }
    return try await self.rescheduleClusterMaintenance(withPolling: request)
  }

  public func listBackupCollections(request: ListBackupCollectionsRequest) async throws
    -> GoogleCloudRedisClusterV1.ListBackupCollectionsResponse
  {
    try await self.listBackupCollections(request: request, options: .init())
  }

  public func listBackupCollections(
    request: ListBackupCollectionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.ListBackupCollectionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listBackupCollections(
    byItem: ListBackupCollectionsRequest
  ) throws -> any AsyncSequence<BackupCollection, Swift.Error> {
    try self.listBackupCollections(byItem: byItem, options: .init())
  }

  public func listBackupCollections(
    byItem: ListBackupCollectionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<BackupCollection, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudRedisClusterV1.ListBackupCollectionsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listBackupCollections(
    parent: Swift.String,
  ) throws -> any AsyncSequence<BackupCollection, Swift.Error> {
    let request = ListBackupCollectionsRequest().with {
      $0.parent = parent
    }
    return try self.listBackupCollections(byItem: request)
  }

  public func getBackupCollection(request: GetBackupCollectionRequest) async throws
    -> GoogleCloudRedisClusterV1.BackupCollection
  {
    try await self.getBackupCollection(request: request, options: .init())
  }

  public func getBackupCollection(
    request: GetBackupCollectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.BackupCollection {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getBackupCollection(
    name: Swift.String,
  ) async throws -> GoogleCloudRedisClusterV1.BackupCollection {
    let request = GetBackupCollectionRequest().with {
      $0.name = name
    }
    return try await self.getBackupCollection(request: request)
  }

  public func listBackups(request: ListBackupsRequest) async throws
    -> GoogleCloudRedisClusterV1.ListBackupsResponse
  {
    try await self.listBackups(request: request, options: .init())
  }

  public func listBackups(
    request: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.ListBackupsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listBackups(
    byItem: ListBackupsRequest
  ) throws -> any AsyncSequence<Backup, Swift.Error> {
    try self.listBackups(byItem: byItem, options: .init())
  }

  public func listBackups(
    byItem: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Backup, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudRedisClusterV1.ListBackupsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listBackups(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Backup, Swift.Error> {
    let request = ListBackupsRequest().with {
      $0.parent = parent
    }
    return try self.listBackups(byItem: request)
  }

  public func getBackup(request: GetBackupRequest) async throws -> GoogleCloudRedisClusterV1.Backup
  {
    try await self.getBackup(request: request, options: .init())
  }

  public func getBackup(
    request: GetBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRedisClusterV1.Backup {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getBackup(
    name: Swift.String,
  ) async throws -> GoogleCloudRedisClusterV1.Backup {
    let request = GetBackupRequest().with {
      $0.name = name
    }
    return try await self.getBackup(request: request)
  }

  public func deleteBackup(request: DeleteBackupRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.deleteBackup(request: request, options: .init())
  }

  public func deleteBackup(
    request: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteBackup(withPolling: DeleteBackupRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteBackup(withPolling: withPolling, options: .init())
  }

  public func deleteBackup(
    withPolling: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteBackup(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteBackupRequest().with {
      $0.name = name
    }
    return try await self.deleteBackup(withPolling: request)
  }

  public func exportBackup(request: ExportBackupRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.exportBackup(request: request, options: .init())
  }

  public func exportBackup(
    request: ExportBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func exportBackup(withPolling: ExportBackupRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Backup>
  {
    try await self.exportBackup(withPolling: withPolling, options: .init())
  }

  public func exportBackup(
    withPolling: ExportBackupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Backup> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Backup>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func backupCluster(request: BackupClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.backupCluster(request: request, options: .init())
  }

  public func backupCluster(
    request: BackupClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func backupCluster(withPolling: BackupClusterRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Cluster>
  {
    try await self.backupCluster(withPolling: withPolling, options: .init())
  }

  public func backupCluster(
    withPolling: BackupClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func backupCluster(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let request = BackupClusterRequest().with {
      $0.name = name
    }
    return try await self.backupCluster(withPolling: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
