// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class CloudRedisClusterTransport: CloudRedisClusterStub {
    let inner: GoogleCloudGax._HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://redis.googleapis.com",
      )
    }

    public func listClusters(
      request: ListClustersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.ListClustersResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/clusters"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudRedisClusterV1.ListClustersResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getCluster(
      request: GetClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.Cluster {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/clusters/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/clusters/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/clusters/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudRedisClusterV1.Cluster.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateCluster(
      request: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.cluster.map({ $0.name }),
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/clusters/"), .singleWildcard,
              ],
              fieldName: "cluster.name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
          query.append(contentsOf: try encoder.encode(request.requestId, prefix: "requestId"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.cluster.map({ $0.name }),
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/clusters/"), .singleWildcard,
            ],
            fieldName: "cluster.name",
            expecting: "projects/*/locations/*/clusters/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.cluster {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteCluster(
      request: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/clusters/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.requestId, prefix: "requestId"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/clusters/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/clusters/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createCluster(
      request: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/clusters"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.clusterId, prefix: "clusterId"))
          query.append(contentsOf: try encoder.encode(request.requestId, prefix: "requestId"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.cluster {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getClusterCertificateAuthority(
      request: GetClusterCertificateAuthorityRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.CertificateAuthority {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/clusters/"), .singleWildcard, .literal("/certificateAuthority"),
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/clusters/"), .singleWildcard, .literal("/certificateAuthority"),
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/clusters/*/certificateAuthority"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudRedisClusterV1.CertificateAuthority.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getSharedRegionalCertificateAuthority(
      request: GetSharedRegionalCertificateAuthorityRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.SharedRegionalCertificateAuthority {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/sharedRegionalCertificateAuthority"),
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/sharedRegionalCertificateAuthority"),
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/sharedRegionalCertificateAuthority"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudRedisClusterV1.SharedRegionalCertificateAuthority.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func rescheduleClusterMaintenance(
      request: RescheduleClusterMaintenanceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure, omitted) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void,
          [Swift.String]
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/clusters/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):rescheduleClusterMaintenance"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/clusters/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/clusters/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request, omitting: omitted)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listBackupCollections(
      request: ListBackupCollectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.ListBackupCollectionsResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/backupCollections"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudRedisClusterV1.ListBackupCollectionsResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func getBackupCollection(
      request: GetBackupCollectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.BackupCollection {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/backupCollections/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/backupCollections/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/backupCollections/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudRedisClusterV1.BackupCollection.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listBackups(
      request: ListBackupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.ListBackupsResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/backupCollections/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/backups"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/backupCollections/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*/backupCollections/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudRedisClusterV1.ListBackupsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getBackup(
      request: GetBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRedisClusterV1.Backup {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/backupCollections/"), .singleWildcard, .literal("/backups/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/backupCollections/"), .singleWildcard, .literal("/backups/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/backupCollections/*/backups/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudRedisClusterV1.Backup.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteBackup(
      request: DeleteBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/backupCollections/"), .singleWildcard, .literal("/backups/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.requestId, prefix: "requestId"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/backupCollections/"), .singleWildcard, .literal("/backups/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/backupCollections/*/backups/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func exportBackup(
      request: ExportBackupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure, omitted) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void,
          [Swift.String]
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/backupCollections/"), .singleWildcard, .literal("/backups/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):export"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/backupCollections/"), .singleWildcard, .literal("/backups/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/backupCollections/*/backups/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request, omitting: omitted)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func backupCluster(
      request: BackupClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure, omitted) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void,
          [Swift.String]
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/clusters/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):backup"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/clusters/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/clusters/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request, omitting: omitted)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/locations"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [.literal("projects/"), .singleWildcard],
            fieldName: "name",
            expecting: "projects/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudLocation.ListLocationsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudLocation.Location.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/operations"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(
            contentsOf: try encoder.encode(
              request.returnPartialSuccess, prefix: "returnPartialSuccess"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.ListOperationsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/operations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/operations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/operations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/operations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleCloudWKT.Empty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):cancel"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/operations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/operations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleCloudWKT.Empty.self, timeout: options.attemptTimeout
      ).get()
    }
  }
}
