// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A cluster instance.
public struct Cluster: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Identifier. Unique name of the resource in this scope including
  /// project and location using the form:
  ///     `projects/{project_id}/locations/{location_id}/clusters/{cluster_id}`
  public var name: Swift.String = Swift.String()

  /// Output only. The timestamp associated with the cluster creation request.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The current state of this cluster.
  /// Can be CREATING, READY, UPDATING, DELETING and SUSPENDED
  public var state: Cluster.State = Cluster.State()

  /// Output only. System assigned, unique identifier for the cluster.
  public var uid: Swift.String = Swift.String()

  /// Optional. The number of replica nodes per shard.
  public var replicaCount: Swift.Int32? = nil

  /// Optional. The authorization mode of the Redis cluster.
  /// If not provided, auth feature is disabled for the cluster.
  public var authorizationMode: AuthorizationMode = AuthorizationMode()

  /// Optional. The in-transit encryption for the Redis cluster.
  /// If not provided, encryption  is disabled for the cluster.
  public var transitEncryptionMode: TransitEncryptionMode = TransitEncryptionMode()

  /// Output only. Redis memory size in GB for the entire cluster rounded up to
  /// the next integer.
  public var sizeGb: Swift.Int32? = nil

  /// Optional. Number of shards for the Redis cluster.
  public var shardCount: Swift.Int32? = nil

  /// Optional. Each PscConfig configures the consumer network where IPs will
  /// be designated to the cluster for client access through Private Service
  /// Connect Automation. Currently, only one PscConfig is supported.
  public var pscConfigs: [PscConfig] = []

  /// Output only. Endpoints created on each given network, for Redis clients to
  /// connect to the cluster. Currently only one discovery endpoint is supported.
  public var discoveryEndpoints: [DiscoveryEndpoint] = []

  /// Output only. The list of PSC connections that are auto-created through
  /// service connectivity automation.
  public var pscConnections: [PscConnection] = []

  /// Output only. Additional information about the current state of the cluster.
  public var stateInfo: Cluster.StateInfo? = nil

  /// Optional. The type of a redis node in the cluster. NodeType determines the
  /// underlying machine-type of a redis node.
  public var nodeType: NodeType = NodeType()

  /// Optional. Persistence config (RDB, AOF) for the cluster.
  public var persistenceConfig: ClusterPersistenceConfig? = nil

  /// Optional. Key/Value pairs of customer overrides for mutable Redis Configs
  public var redisConfigs: [Swift.String: Swift.String] = [:]

  /// Output only. Precise value of redis memory size in GB for the entire
  /// cluster.
  public var preciseSizeGb: Swift.Double? = nil

  /// Optional. This config will be used to determine how the customer wants us
  /// to distribute cluster resources within the region.
  public var zoneDistributionConfig: ZoneDistributionConfig? = nil

  /// Optional. Cross cluster replication config.
  public var crossClusterReplicationConfig: CrossClusterReplicationConfig? = nil

  /// Optional. The delete operation will fail when the value is set to true.
  public var deletionProtectionEnabled: Swift.Bool? = nil

  /// Optional. ClusterMaintenancePolicy determines when to allow or deny
  /// updates.
  public var maintenancePolicy: ClusterMaintenancePolicy? = nil

  /// Output only. ClusterMaintenanceSchedule Output only Published maintenance
  /// schedule.
  public var maintenanceSchedule: ClusterMaintenanceSchedule? = nil

  /// Output only. Service attachment details to configure Psc connections
  public var pscServiceAttachments: [PscServiceAttachment] = []

  /// Optional. A list of cluster enpoints.
  public var clusterEndpoints: [ClusterEndpoint] = []

  /// Optional. Output only. The backup collection full resource name. Example:
  /// projects/{project}/locations/{location}/backupCollections/{collection}
  public var backupCollection: Swift.String? = nil

  /// Optional. The KMS key used to encrypt the at-rest data of the cluster.
  public var kmsKey: Swift.String? = nil

  /// Optional. The automated backup config for the cluster.
  public var automatedBackupConfig: AutomatedBackupConfig? = nil

  /// Output only. Encryption information of the data at rest of the cluster.
  public var encryptionInfo: EncryptionInfo? = nil

  /// Optional. If true, cluster endpoints that are created and registered by
  /// customers can be deleted asynchronously. That is, such a cluster endpoint
  /// can be de-registered before the forwarding rules in the cluster endpoint
  /// are deleted.
  public var asyncClusterEndpointsDeletionEnabled: Swift.Bool? = nil

  /// Optional. Server CA mode for the cluster.
  public var serverCaMode: ServerCaMode? = nil

  /// Optional. Customer-managed CA pool for the cluster. Only applicable for
  /// BYOCA i.e. if server_ca_mode is SERVER_CA_MODE_CUSTOMER_MANAGED_CAS_CA.
  /// Format: "projects/{project}/locations/{region}/caPools/{ca_pool}".
  public var serverCaPool: Swift.String? = nil

  /// Optional. Input only. Rotate the server certificates.
  public var rotateServerCertificate: Swift.Bool? = nil

  /// The source to import from.
  public var importSources: OneOf_ImportSources? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Cluster`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Cluster().with { $0.gcsSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gcsSource = CodingKeys(stringValue: "gcsSource")
    static let managedBackupSource = CodingKeys(stringValue: "managedBackupSource")
    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let state = CodingKeys(stringValue: "state")
    static let uid = CodingKeys(stringValue: "uid")
    static let replicaCount = CodingKeys(stringValue: "replicaCount")
    static let authorizationMode = CodingKeys(stringValue: "authorizationMode")
    static let transitEncryptionMode = CodingKeys(stringValue: "transitEncryptionMode")
    static let sizeGb = CodingKeys(stringValue: "sizeGb")
    static let shardCount = CodingKeys(stringValue: "shardCount")
    static let pscConfigs = CodingKeys(stringValue: "pscConfigs")
    static let discoveryEndpoints = CodingKeys(stringValue: "discoveryEndpoints")
    static let pscConnections = CodingKeys(stringValue: "pscConnections")
    static let stateInfo = CodingKeys(stringValue: "stateInfo")
    static let nodeType = CodingKeys(stringValue: "nodeType")
    static let persistenceConfig = CodingKeys(stringValue: "persistenceConfig")
    static let redisConfigs = CodingKeys(stringValue: "redisConfigs")
    static let preciseSizeGb = CodingKeys(stringValue: "preciseSizeGb")
    static let zoneDistributionConfig = CodingKeys(stringValue: "zoneDistributionConfig")
    static let crossClusterReplicationConfig = CodingKeys(
      stringValue: "crossClusterReplicationConfig")
    static let deletionProtectionEnabled = CodingKeys(stringValue: "deletionProtectionEnabled")
    static let maintenancePolicy = CodingKeys(stringValue: "maintenancePolicy")
    static let maintenanceSchedule = CodingKeys(stringValue: "maintenanceSchedule")
    static let pscServiceAttachments = CodingKeys(stringValue: "pscServiceAttachments")
    static let clusterEndpoints = CodingKeys(stringValue: "clusterEndpoints")
    static let backupCollection = CodingKeys(stringValue: "backupCollection")
    static let kmsKey = CodingKeys(stringValue: "kmsKey")
    static let automatedBackupConfig = CodingKeys(stringValue: "automatedBackupConfig")
    static let encryptionInfo = CodingKeys(stringValue: "encryptionInfo")
    static let asyncClusterEndpointsDeletionEnabled = CodingKeys(
      stringValue: "asyncClusterEndpointsDeletionEnabled")
    static let serverCaMode = CodingKeys(stringValue: "serverCaMode")
    static let serverCaPool = CodingKeys(stringValue: "serverCaPool")
    static let rotateServerCertificate = CodingKeys(stringValue: "rotateServerCertificate")

    static let _knownKeys: Set<Swift.String> = [
      "gcsSource",
      "managedBackupSource",
      "name",
      "createTime",
      "state",
      "uid",
      "replicaCount",
      "authorizationMode",
      "transitEncryptionMode",
      "sizeGb",
      "shardCount",
      "pscConfigs",
      "discoveryEndpoints",
      "pscConnections",
      "stateInfo",
      "nodeType",
      "persistenceConfig",
      "redisConfigs",
      "preciseSizeGb",
      "zoneDistributionConfig",
      "crossClusterReplicationConfig",
      "deletionProtectionEnabled",
      "maintenancePolicy",
      "maintenanceSchedule",
      "pscServiceAttachments",
      "clusterEndpoints",
      "backupCollection",
      "kmsKey",
      "automatedBackupConfig",
      "encryptionInfo",
      "asyncClusterEndpointsDeletionEnabled",
      "serverCaMode",
      "serverCaPool",
      "rotateServerCertificate",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent(Cluster.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    self.replicaCount = try container.decodeIfPresent(Swift.Int32.self, forKey: .replicaCount)
    if let value = try container.decodeIfPresent(AuthorizationMode.self, forKey: .authorizationMode)
    {
      self.authorizationMode = value
    }
    if let value = try container.decodeIfPresent(
      TransitEncryptionMode.self, forKey: .transitEncryptionMode)
    {
      self.transitEncryptionMode = value
    }
    self.sizeGb = try container.decodeIfPresent(Swift.Int32.self, forKey: .sizeGb)
    self.shardCount = try container.decodeIfPresent(Swift.Int32.self, forKey: .shardCount)
    if let value = try container.decodeIfPresent([PscConfig].self, forKey: .pscConfigs) {
      self.pscConfigs = value
    }
    if let value = try container.decodeIfPresent(
      [DiscoveryEndpoint].self, forKey: .discoveryEndpoints)
    {
      self.discoveryEndpoints = value
    }
    if let value = try container.decodeIfPresent([PscConnection].self, forKey: .pscConnections) {
      self.pscConnections = value
    }
    self.stateInfo = try container.decodeIfPresent(Cluster.StateInfo.self, forKey: .stateInfo)
    if let value = try container.decodeIfPresent(NodeType.self, forKey: .nodeType) {
      self.nodeType = value
    }
    self.persistenceConfig = try container.decodeIfPresent(
      ClusterPersistenceConfig.self, forKey: .persistenceConfig)
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .redisConfigs)
    {
      self.redisConfigs = value
    }
    self.preciseSizeGb = try container.decodeIfPresent(Swift.Double.self, forKey: .preciseSizeGb)
    self.zoneDistributionConfig = try container.decodeIfPresent(
      ZoneDistributionConfig.self, forKey: .zoneDistributionConfig)
    self.crossClusterReplicationConfig = try container.decodeIfPresent(
      CrossClusterReplicationConfig.self, forKey: .crossClusterReplicationConfig)
    self.deletionProtectionEnabled = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .deletionProtectionEnabled)
    self.maintenancePolicy = try container.decodeIfPresent(
      ClusterMaintenancePolicy.self, forKey: .maintenancePolicy)
    self.maintenanceSchedule = try container.decodeIfPresent(
      ClusterMaintenanceSchedule.self, forKey: .maintenanceSchedule)
    if let value = try container.decodeIfPresent(
      [PscServiceAttachment].self, forKey: .pscServiceAttachments)
    {
      self.pscServiceAttachments = value
    }
    if let value = try container.decodeIfPresent([ClusterEndpoint].self, forKey: .clusterEndpoints)
    {
      self.clusterEndpoints = value
    }
    self.backupCollection = try container.decodeIfPresent(
      Swift.String.self, forKey: .backupCollection)
    self.kmsKey = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKey)
    self.automatedBackupConfig = try container.decodeIfPresent(
      AutomatedBackupConfig.self, forKey: .automatedBackupConfig)
    self.encryptionInfo = try container.decodeIfPresent(
      EncryptionInfo.self, forKey: .encryptionInfo)
    self.asyncClusterEndpointsDeletionEnabled = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .asyncClusterEndpointsDeletionEnabled)
    self.serverCaMode = try container.decodeIfPresent(ServerCaMode.self, forKey: .serverCaMode)
    self.serverCaPool = try container.decodeIfPresent(Swift.String.self, forKey: .serverCaPool)
    self.rotateServerCertificate = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .rotateServerCertificate)

    var importSources: OneOf_ImportSources? = nil
    let importSourcesCheckAndSet = {
      if importSources != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'importSources'"))
      }
      importSources = $0
    }
    if let gcsSource = try container.decodeIfPresent(
      Cluster.GcsBackupSource?.self, forKey: .gcsSource)
    {
      try importSourcesCheckAndSet(.gcsSource(gcsSource))
    }
    if let managedBackupSource = try container.decodeIfPresent(
      Cluster.ManagedBackupSource?.self, forKey: .managedBackupSource)
    {
      try importSourcesCheckAndSet(.managedBackupSource(managedBackupSource))
    }
    self.importSources = importSources
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.uid, forKey: .uid)
    try container.encodeIfPresent(self.replicaCount, forKey: .replicaCount)
    try container.encode(self.authorizationMode, forKey: .authorizationMode)
    try container.encode(self.transitEncryptionMode, forKey: .transitEncryptionMode)
    try container.encodeIfPresent(self.sizeGb, forKey: .sizeGb)
    try container.encodeIfPresent(self.shardCount, forKey: .shardCount)
    try container.encode(self.pscConfigs, forKey: .pscConfigs)
    try container.encode(self.discoveryEndpoints, forKey: .discoveryEndpoints)
    try container.encode(self.pscConnections, forKey: .pscConnections)
    try container.encodeIfPresent(self.stateInfo, forKey: .stateInfo)
    try container.encode(self.nodeType, forKey: .nodeType)
    try container.encodeIfPresent(self.persistenceConfig, forKey: .persistenceConfig)
    try container.encode(self.redisConfigs, forKey: .redisConfigs)
    try container.encodeIfPresent(self.preciseSizeGb, forKey: .preciseSizeGb)
    try container.encodeIfPresent(self.zoneDistributionConfig, forKey: .zoneDistributionConfig)
    try container.encodeIfPresent(
      self.crossClusterReplicationConfig, forKey: .crossClusterReplicationConfig)
    try container.encodeIfPresent(
      self.deletionProtectionEnabled, forKey: .deletionProtectionEnabled)
    try container.encodeIfPresent(self.maintenancePolicy, forKey: .maintenancePolicy)
    try container.encodeIfPresent(self.maintenanceSchedule, forKey: .maintenanceSchedule)
    try container.encode(self.pscServiceAttachments, forKey: .pscServiceAttachments)
    try container.encode(self.clusterEndpoints, forKey: .clusterEndpoints)
    try container.encodeIfPresent(self.backupCollection, forKey: .backupCollection)
    try container.encodeIfPresent(self.kmsKey, forKey: .kmsKey)
    try container.encodeIfPresent(self.automatedBackupConfig, forKey: .automatedBackupConfig)
    try container.encodeIfPresent(self.encryptionInfo, forKey: .encryptionInfo)
    try container.encodeIfPresent(
      self.asyncClusterEndpointsDeletionEnabled, forKey: .asyncClusterEndpointsDeletionEnabled)
    try container.encodeIfPresent(self.serverCaMode, forKey: .serverCaMode)
    try container.encodeIfPresent(self.serverCaPool, forKey: .serverCaPool)
    try container.encodeIfPresent(self.rotateServerCertificate, forKey: .rotateServerCertificate)

    if let choice = self.importSources {
      switch choice {
      case .gcsSource(let value):
        try container.encode(value, forKey: .gcsSource)
      case .managedBackupSource(let value):
        try container.encode(value, forKey: .managedBackupSource)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Represents additional information about the state of the cluster.
  public struct StateInfo: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    public var info: OneOf_Info? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `StateInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StateInfo().with { $0.updateInfo = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let updateInfo = CodingKeys(stringValue: "updateInfo")

      static let _knownKeys: Set<Swift.String> = [
        "updateInfo"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var info: OneOf_Info? = nil
      let infoCheckAndSet = {
        if info != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'info'"))
        }
        info = $0
      }
      if let updateInfo = try container.decodeIfPresent(
        Cluster.StateInfo.UpdateInfo?.self, forKey: .updateInfo)
      {
        try infoCheckAndSet(.updateInfo(updateInfo))
      }
      self.info = info
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.info {
        switch choice {
        case .updateInfo(let value):
          try container.encode(value, forKey: .updateInfo)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Represents information about an updating cluster.
    public struct UpdateInfo: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Target number of shards for redis cluster
      public var targetShardCount: Swift.Int32? = nil

      /// Target number of replica nodes per shard.
      public var targetReplicaCount: Swift.Int32? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

      /// Initialize a new instance of `UpdateInfo`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = UpdateInfo().with { $0.targetShardCount = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let targetShardCount = CodingKeys(stringValue: "targetShardCount")
        static let targetReplicaCount = CodingKeys(stringValue: "targetReplicaCount")

        static let _knownKeys: Set<Swift.String> = [
          "targetShardCount",
          "targetReplicaCount",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.targetShardCount = try container.decodeIfPresent(
          Swift.Int32.self, forKey: .targetShardCount)
        self.targetReplicaCount = try container.decodeIfPresent(
          Swift.Int32.self, forKey: .targetReplicaCount)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleCloudWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.targetShardCount, forKey: .targetShardCount)
        try container.encodeIfPresent(self.targetReplicaCount, forKey: .targetReplicaCount)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.redis.cluster.v1.Cluster.StateInfo.UpdateInfo"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    public enum OneOf_Info: Codable, Equatable, Sendable {
      /// Describes ongoing update on the cluster when cluster state is UPDATING.
      indirect case updateInfo(Cluster.StateInfo.UpdateInfo?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.redis.cluster.v1.Cluster.StateInfo"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Backups stored in Cloud Storage buckets.
  /// The Cloud Storage buckets need to be the same region as the clusters.
  public struct GcsBackupSource: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. URIs of the GCS objects to import.
    /// Example: gs://bucket1/object1, gs://bucket2/folder2/object2
    public var uris: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `GcsBackupSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GcsBackupSource().with { $0.uris = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let uris = CodingKeys(stringValue: "uris")

      static let _knownKeys: Set<Swift.String> = [
        "uris"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .uris) {
        self.uris = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.uris, forKey: .uris)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.redis.cluster.v1.Cluster.GcsBackupSource"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Backups that generated and managed by memorystore.
  public struct ManagedBackupSource: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. Example:
    /// //redis.googleapis.com/projects/{project}/locations/{location}/backupCollections/{collection}/backups/{backup}
    /// A shorter version (without the prefix) of the backup name is also
    /// supported, like
    /// projects/{project}/locations/{location}/backupCollections/{collection}/backups/{backup_id}
    /// In this case, it assumes the backup is under redis.googleapis.com.
    public var backup: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `ManagedBackupSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ManagedBackupSource().with { $0.backup = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let backup = CodingKeys(stringValue: "backup")

      static let _knownKeys: Set<Swift.String> = [
        "backup"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backup) {
        self.backup = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.backup, forKey: .backup)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.redis.cluster.v1.Cluster.ManagedBackupSource"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Represents the different states of a Redis cluster.
  public enum State: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// Redis cluster is being created.
    case creating
    /// Redis cluster has been created and is fully usable.
    case active
    /// Redis cluster configuration is being updated.
    case updating
    /// Redis cluster is being deleted.
    case deleting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .updating: return 3
      case .deleting: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .updating: return "UPDATING"
      case .deleting: return "DELETING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "UPDATING": self = .updating
      case "DELETING": self = .deleting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .updating
      case 4: self = .deleting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .creating: return try container.encode("CREATING")
      case .active: return try container.encode("ACTIVE")
      case .updating: return try container.encode("UPDATING")
      case .deleting: return try container.encode("DELETING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The source to import from.
  public enum OneOf_ImportSources: Codable, Equatable, Sendable {
    /// Optional. Backups stored in Cloud Storage buckets.
    /// The Cloud Storage buckets need to be the same region as the clusters.
    /// Read permission is required to import from the provided Cloud Storage
    /// objects.
    indirect case gcsSource(Cluster.GcsBackupSource?)
    /// Optional. Backups generated and managed by memorystore service.
    indirect case managedBackupSource(Cluster.ManagedBackupSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.redis.cluster.v1.Cluster"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
