// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Detailed information of each PSC connection.
public struct ConnectionDetail: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A PSC connection to a cluster could either be created through Service
  /// Connectivity Automation (auto-registered connection) during the cluster
  /// creation, or it could be created by customer themselves (user-registered
  /// connection).
  public var connection: OneOf_Connection? = nil

  /// Initialize a new instance of `ConnectionDetail`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConnectionDetail().with { $0.pscAutoConnection = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case pscAutoConnection = "pscAutoConnection"
    case pscConnection = "pscConnection"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var connection: OneOf_Connection? = nil
    let connectionCheckAndSet = {
      if connection != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'connection'"))
      }
      connection = $0
    }
    if let pscAutoConnection = try container.decodeIfPresent(
      PscAutoConnection?.self, forKey: .pscAutoConnection)
    {
      try connectionCheckAndSet(.pscAutoConnection(pscAutoConnection))
    }
    if let pscConnection = try container.decodeIfPresent(
      PscConnection?.self, forKey: .pscConnection)
    {
      try connectionCheckAndSet(.pscConnection(pscConnection))
    }
    self.connection = connection
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.connection {
      switch choice {
      case .pscAutoConnection(let value):
        try container.encode(value, forKey: .pscAutoConnection)
      case .pscConnection(let value):
        try container.encode(value, forKey: .pscConnection)
      }
    }
  }

  /// A PSC connection to a cluster could either be created through Service
  /// Connectivity Automation (auto-registered connection) during the cluster
  /// creation, or it could be created by customer themselves (user-registered
  /// connection).
  public enum OneOf_Connection: Codable, Equatable, Sendable {
    /// Detailed information of a PSC connection that is created through
    /// service connectivity automation.
    indirect case pscAutoConnection(PscAutoConnection?)
    /// Detailed information of a PSC connection that is created by the customer
    /// who owns the cluster.
    indirect case pscConnection(PscConnection?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.redis.cluster.v1.ConnectionDetail"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
