// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Cross cluster replication config.
public struct CrossClusterReplicationConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The role of the cluster in cross cluster replication.
  public var clusterRole: CrossClusterReplicationConfig.ClusterRole =
    CrossClusterReplicationConfig.ClusterRole()

  /// Details of the primary cluster that is used as the replication source for
  /// this secondary cluster.
  ///
  /// This field is only set for a secondary cluster.
  public var primaryCluster: CrossClusterReplicationConfig.RemoteCluster? = nil

  /// List of secondary clusters that are replicating from this primary cluster.
  ///
  /// This field is only set for a primary cluster.
  public var secondaryClusters: [CrossClusterReplicationConfig.RemoteCluster] = []

  /// Output only. The last time cross cluster replication config was updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. An output only view of all the member clusters participating
  /// in the cross cluster replication. This view will be provided by every
  /// member cluster irrespective of its cluster role(primary or secondary).
  ///
  /// A primary cluster can provide information about all the secondary clusters
  /// replicating from it. However, a secondary cluster only knows about the
  /// primary cluster from which it is replicating. However, for scenarios, where
  /// the primary cluster is unavailable(e.g. regional outage), a GetCluster
  /// request can be sent to any other member cluster and this field will list
  /// all the member clusters participating in cross cluster replication.
  public var membership: CrossClusterReplicationConfig.Membership? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CrossClusterReplicationConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CrossClusterReplicationConfig().with { $0.clusterRole = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let clusterRole = CodingKeys(stringValue: "clusterRole")
    static let primaryCluster = CodingKeys(stringValue: "primaryCluster")
    static let secondaryClusters = CodingKeys(stringValue: "secondaryClusters")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let membership = CodingKeys(stringValue: "membership")

    static let _knownKeys: Set<Swift.String> = [
      "clusterRole",
      "primaryCluster",
      "secondaryClusters",
      "updateTime",
      "membership",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      CrossClusterReplicationConfig.ClusterRole.self, forKey: .clusterRole)
    {
      self.clusterRole = value
    }
    self.primaryCluster = try container.decodeIfPresent(
      CrossClusterReplicationConfig.RemoteCluster.self, forKey: .primaryCluster)
    if let value = try container.decodeIfPresent(
      [CrossClusterReplicationConfig.RemoteCluster].self, forKey: .secondaryClusters)
    {
      self.secondaryClusters = value
    }
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    self.membership = try container.decodeIfPresent(
      CrossClusterReplicationConfig.Membership.self, forKey: .membership)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.clusterRole, forKey: .clusterRole)
    try container.encodeIfPresent(self.primaryCluster, forKey: .primaryCluster)
    try container.encode(self.secondaryClusters, forKey: .secondaryClusters)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.membership, forKey: .membership)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Details of the remote cluster associated with this cluster in a cross
  /// cluster replication setup.
  public struct RemoteCluster: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The full resource path of the remote cluster in
    /// the format: projects/<project>/locations/<region>/clusters/<cluster-id>
    public var cluster: Swift.String = Swift.String()

    /// Output only. The unique identifier of the remote cluster.
    public var uid: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RemoteCluster`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RemoteCluster().with { $0.cluster = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let cluster = CodingKeys(stringValue: "cluster")
      static let uid = CodingKeys(stringValue: "uid")

      static let _knownKeys: Set<Swift.String> = [
        "cluster",
        "uid",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cluster) {
        self.cluster = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
        self.uid = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.cluster, forKey: .cluster)
      try container.encode(self.uid, forKey: .uid)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.redis.cluster.v1.CrossClusterReplicationConfig.RemoteCluster"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// An output only view of all the member clusters participating in the cross
  /// cluster replication.
  public struct Membership: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The primary cluster that acts as the source of replication
    /// for the secondary clusters.
    public var primaryCluster: CrossClusterReplicationConfig.RemoteCluster? = nil

    /// Output only. The list of secondary clusters replicating from the primary
    /// cluster.
    public var secondaryClusters: [CrossClusterReplicationConfig.RemoteCluster] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Membership`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Membership().with { $0.primaryCluster = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let primaryCluster = CodingKeys(stringValue: "primaryCluster")
      static let secondaryClusters = CodingKeys(stringValue: "secondaryClusters")

      static let _knownKeys: Set<Swift.String> = [
        "primaryCluster",
        "secondaryClusters",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.primaryCluster = try container.decodeIfPresent(
        CrossClusterReplicationConfig.RemoteCluster.self, forKey: .primaryCluster)
      if let value = try container.decodeIfPresent(
        [CrossClusterReplicationConfig.RemoteCluster].self, forKey: .secondaryClusters)
      {
        self.secondaryClusters = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.primaryCluster, forKey: .primaryCluster)
      try container.encode(self.secondaryClusters, forKey: .secondaryClusters)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.redis.cluster.v1.CrossClusterReplicationConfig.Membership"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The role of the cluster in cross cluster replication.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ClusterRole: Codable, Equatable, Sendable {
    /// Cluster role is not set.
    /// The behavior is equivalent to NONE.
    case unspecified
    /// This cluster does not participate in cross cluster replication. It is an
    /// independent cluster and does not replicate to or from any other clusters.
    case `none`
    /// A cluster that allows both reads and writes. Any data written to this
    /// cluster is also replicated to the attached secondary clusters.
    case primary
    /// A cluster that allows only reads and replicates data from a primary
    /// cluster.
    case secondary
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`none`: return 1
      case .primary: return 2
      case .secondary: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CLUSTER_ROLE_UNSPECIFIED"
      case .`none`: return "NONE"
      case .primary: return "PRIMARY"
      case .secondary: return "SECONDARY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ClusterRole/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CLUSTER_ROLE_UNSPECIFIED": self = .unspecified
      case "NONE": self = .`none`
      case "PRIMARY": self = .primary
      case "SECONDARY": self = .secondary
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ClusterRole/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`none`
      case 2: self = .primary
      case 3: self = .secondary
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CLUSTER_ROLE_UNSPECIFIED")
      case .`none`: return try container.encode("NONE")
      case .primary: return try container.encode("PRIMARY")
      case .secondary: return try container.encode("SECONDARY")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.redis.cluster.v1.CrossClusterReplicationConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
