// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// NodeType of a redis cluster node,
public enum NodeType: Codable, Equatable, Sendable {
  /// Node type unspecified
  case unspecified
  /// Redis shared core nano node_type.
  case redisSharedCoreNano
  /// Redis highmem medium node_type.
  case redisHighmemMedium
  /// Redis highmem xlarge node_type.
  case redisHighmemXlarge
  /// Redis standard small node_type.
  case redisStandardSmall
  /// Redis highcpu medium node_type.
  case redisHighcpuMedium
  /// Redis standard large node_type.
  case redisStandardLarge
  /// Redis highmem 2xlarge node_type.
  case redisHighmem2Xlarge
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .redisSharedCoreNano: return 1
    case .redisHighmemMedium: return 2
    case .redisHighmemXlarge: return 3
    case .redisStandardSmall: return 4
    case .redisHighcpuMedium: return 7
    case .redisStandardLarge: return 8
    case .redisHighmem2Xlarge: return 9
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "NODE_TYPE_UNSPECIFIED"
    case .redisSharedCoreNano: return "REDIS_SHARED_CORE_NANO"
    case .redisHighmemMedium: return "REDIS_HIGHMEM_MEDIUM"
    case .redisHighmemXlarge: return "REDIS_HIGHMEM_XLARGE"
    case .redisStandardSmall: return "REDIS_STANDARD_SMALL"
    case .redisHighcpuMedium: return "REDIS_HIGHCPU_MEDIUM"
    case .redisStandardLarge: return "REDIS_STANDARD_LARGE"
    case .redisHighmem2Xlarge: return "REDIS_HIGHMEM_2XLARGE"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:NodeType/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "NODE_TYPE_UNSPECIFIED": self = .unspecified
    case "REDIS_SHARED_CORE_NANO": self = .redisSharedCoreNano
    case "REDIS_HIGHMEM_MEDIUM": self = .redisHighmemMedium
    case "REDIS_HIGHMEM_XLARGE": self = .redisHighmemXlarge
    case "REDIS_STANDARD_SMALL": self = .redisStandardSmall
    case "REDIS_HIGHCPU_MEDIUM": self = .redisHighcpuMedium
    case "REDIS_STANDARD_LARGE": self = .redisStandardLarge
    case "REDIS_HIGHMEM_2XLARGE": self = .redisHighmem2Xlarge
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:NodeType/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .redisSharedCoreNano
    case 2: self = .redisHighmemMedium
    case 3: self = .redisHighmemXlarge
    case 4: self = .redisStandardSmall
    case 7: self = .redisHighcpuMedium
    case 8: self = .redisStandardLarge
    case 9: self = .redisHighmem2Xlarge
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .redisSharedCoreNano: return try container.encode(1)
    case .redisHighmemMedium: return try container.encode(2)
    case .redisHighmemXlarge: return try container.encode(3)
    case .redisStandardSmall: return try container.encode(4)
    case .redisHighcpuMedium: return try container.encode(7)
    case .redisStandardLarge: return try container.encode(8)
    case .redisHighmem2Xlarge: return try container.encode(9)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
