// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Details of consumer resources in a PSC connection that is created through
/// Service Connectivity Automation.
public struct PscAutoConnection: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The PSC connection id of the forwarding rule connected to the
  /// service attachment.
  public var pscConnectionId: Swift.String = Swift.String()

  /// Output only. The IP allocated on the consumer network for the PSC
  /// forwarding rule.
  public var address: Swift.String = Swift.String()

  /// Output only. The URI of the consumer side forwarding rule.
  /// Example:
  /// projects/{projectNumOrId}/regions/us-east1/forwardingRules/{resourceId}.
  public var forwardingRule: Swift.String = Swift.String()

  /// Required. The consumer project_id where the forwarding rule is created
  /// from.
  public var projectId: Swift.String = Swift.String()

  /// Required. The consumer network where the IP address resides, in the form of
  /// projects/{project_id}/global/networks/{network_id}.
  public var network: Swift.String = Swift.String()

  /// Output only. The service attachment which is the target of the PSC
  /// connection, in the form of
  /// projects/{project-id}/regions/{region}/serviceAttachments/{service-attachment-id}.
  public var serviceAttachment: Swift.String = Swift.String()

  /// Output only. The status of the PSC connection.
  /// Please note that this value is updated periodically.
  /// Please use Private Service Connect APIs for the latest status.
  public var pscConnectionStatus: PscConnectionStatus = PscConnectionStatus()

  /// Output only. Type of the PSC connection.
  public var connectionType: ConnectionType = ConnectionType()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PscAutoConnection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PscAutoConnection().with { $0.pscConnectionId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let pscConnectionId = CodingKeys(stringValue: "pscConnectionId")
    static let address = CodingKeys(stringValue: "address")
    static let forwardingRule = CodingKeys(stringValue: "forwardingRule")
    static let projectId = CodingKeys(stringValue: "projectId")
    static let network = CodingKeys(stringValue: "network")
    static let serviceAttachment = CodingKeys(stringValue: "serviceAttachment")
    static let pscConnectionStatus = CodingKeys(stringValue: "pscConnectionStatus")
    static let connectionType = CodingKeys(stringValue: "connectionType")

    static let _knownKeys: Set<Swift.String> = [
      "pscConnectionId",
      "address",
      "forwardingRule",
      "projectId",
      "network",
      "serviceAttachment",
      "pscConnectionStatus",
      "connectionType",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pscConnectionId) {
      self.pscConnectionId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .address) {
      self.address = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .forwardingRule) {
      self.forwardingRule = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
      self.projectId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
      self.network = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAttachment) {
      self.serviceAttachment = value
    }
    if let value = try container.decodeIfPresent(
      PscConnectionStatus.self, forKey: .pscConnectionStatus)
    {
      self.pscConnectionStatus = value
    }
    if let value = try container.decodeIfPresent(ConnectionType.self, forKey: .connectionType) {
      self.connectionType = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.pscConnectionId, forKey: .pscConnectionId)
    try container.encode(self.address, forKey: .address)
    try container.encode(self.forwardingRule, forKey: .forwardingRule)
    try container.encode(self.projectId, forKey: .projectId)
    try container.encode(self.network, forKey: .network)
    try container.encode(self.serviceAttachment, forKey: .serviceAttachment)
    try container.encode(self.pscConnectionStatus, forKey: .pscConnectionStatus)
    try container.encode(self.connectionType, forKey: .connectionType)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.redis.cluster.v1.PscAutoConnection"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
