// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Details of consumer resources in a PSC connection.
public struct PscConnection: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The PSC connection id of the forwarding rule connected to the
  /// service attachment.
  public var pscConnectionId: Swift.String = Swift.String()

  /// Required. The IP allocated on the consumer network for the PSC forwarding
  /// rule.
  public var address: Swift.String = Swift.String()

  /// Required. The URI of the consumer side forwarding rule.
  /// Example:
  /// projects/{projectNumOrId}/regions/us-east1/forwardingRules/{resourceId}.
  public var forwardingRule: Swift.String = Swift.String()

  /// Optional. Project ID of the consumer project where the forwarding rule is
  /// created in.
  public var projectId: Swift.String = Swift.String()

  /// Required. The consumer network where the IP address resides, in the form of
  /// projects/{project_id}/global/networks/{network_id}.
  public var network: Swift.String = Swift.String()

  /// Required. The service attachment which is the target of the PSC connection,
  /// in the form of
  /// projects/{project-id}/regions/{region}/serviceAttachments/{service-attachment-id}.
  public var serviceAttachment: Swift.String = Swift.String()

  /// Output only. The status of the PSC connection.
  /// Please note that this value is updated periodically.
  /// To get the latest status of a PSC connection, follow
  /// https://cloud.google.com/vpc/docs/configure-private-service-connect-services#endpoint-details.
  public var pscConnectionStatus: PscConnectionStatus = PscConnectionStatus()

  /// Output only. Type of the PSC connection.
  public var connectionType: ConnectionType = ConnectionType()

  /// Initialize a new instance of `PscConnection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PscConnection().with { $0.pscConnectionId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.redis.cluster.v1.PscConnection"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
