// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Server CA mode for the cluster.
public enum ServerCaMode: Codable, Equatable, Sendable {
  /// Server CA mode not specified.
  case unspecified
  /// Each cluster has its own Google managed CA.
  case googleManagedPerInstanceCa
  /// The cluster uses Google managed shared CA in the region.
  case googleManagedSharedCa
  /// The cluster uses customer managed CA from CAS.
  case customerManagedCasCa
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .googleManagedPerInstanceCa: return 1
    case .googleManagedSharedCa: return 2
    case .customerManagedCasCa: return 3
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "SERVER_CA_MODE_UNSPECIFIED"
    case .googleManagedPerInstanceCa: return "SERVER_CA_MODE_GOOGLE_MANAGED_PER_INSTANCE_CA"
    case .googleManagedSharedCa: return "SERVER_CA_MODE_GOOGLE_MANAGED_SHARED_CA"
    case .customerManagedCasCa: return "SERVER_CA_MODE_CUSTOMER_MANAGED_CAS_CA"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ServerCaMode/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "SERVER_CA_MODE_UNSPECIFIED": self = .unspecified
    case "SERVER_CA_MODE_GOOGLE_MANAGED_PER_INSTANCE_CA": self = .googleManagedPerInstanceCa
    case "SERVER_CA_MODE_GOOGLE_MANAGED_SHARED_CA": self = .googleManagedSharedCa
    case "SERVER_CA_MODE_CUSTOMER_MANAGED_CAS_CA": self = .customerManagedCasCa
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ServerCaMode/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .googleManagedPerInstanceCa
    case 2: self = .googleManagedSharedCa
    case 3: self = .customerManagedCasCa
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .googleManagedPerInstanceCa: return try container.encode(1)
    case .googleManagedSharedCa: return try container.encode(2)
    case .customerManagedCasCa: return try container.encode(3)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
